// web/src/lib/components/frameleaf/SharedLinkForm.svelte
<script lang="ts">
  import AssetCollage from './AssetCollage.svelte';
  import Dialog from './Dialog.svelte';
  import QrCode from './QrCode.svelte';
  import { sharedLinkBadges, relativeTime, type SharedLinkBadgeId } from '$lib/frameleaf/shared-link-badges';
  import { asUrl, handleCreateSharedLink, handleUpdateSharedLink } from '$lib/services/shared-link.service';
  import { locale } from '$lib/stores/preferences.store';
  import { getAllSharedLinks, SharedLinkType, type SharedLinkResponseDto } from '@frameleaf/sdk';
  import { Icon } from '@frameleaf/ui';
  import {
    mdiClockOutline,
    mdiContentCopy,
    mdiDownloadOutline,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiInformationOutline,
    mdiLinkVariant,
    mdiLockOutline,
    mdiOpenInNew,
    mdiQrcode,
    mdiUpload,
  } from '@mdi/js';
  import { t } from 'svelte-i18n';

  /**
   * Create or edit a shared link: the design's `SharedLinkForm` (`SharedLinkForm.jsx:88-509`).
   *
   * As in the design, a new link does not show camera and location details unless asked
   * (`SharedLinkForm.jsx:108`). Downloads stay tied to metadata, as upstream: the server serves
   * originals byte for byte, embedded EXIF and GPS included, so a link that hides metadata must
   * not offer downloads. With metadata off by default, download is off by default too.
   * Creating ends on the design's "Link ready" step (address, Copy, QR code, Open) in place of
   * the legacy QR modal; editing saves and closes.
   */
  const MINUTE = 60_000;
  const HOUR = 60 * MINUTE;
  const DAY = 24 * HOUR;

  type Preset = { id: string; ms: number | null; value?: number; unit?: 'minute' | 'hour' | 'day' | 'month' | 'year' };
  const PRESETS: Preset[] = [
    { id: '30m', ms: 30 * MINUTE, value: 30, unit: 'minute' },
    { id: '1h', ms: HOUR, value: 1, unit: 'hour' },
    { id: '6h', ms: 6 * HOUR, value: 6, unit: 'hour' },
    { id: '1d', ms: DAY, value: 1, unit: 'day' },
    { id: '7d', ms: 7 * DAY, value: 7, unit: 'day' },
    { id: '30d', ms: 30 * DAY, value: 30, unit: 'day' },
    { id: '3mo', ms: 90 * DAY, value: 3, unit: 'month' },
    { id: '1y', ms: 365 * DAY, value: 1, unit: 'year' },
    { id: 'never', ms: null },
  ];

  let {
    open = $bindable(false),
    target,
    link,
    onClosed,
  }: {
    open?: boolean;
    target?: {
      type: SharedLinkType;
      albumId?: string;
      assetIds?: string[];
      name: string;
      /** For an album, the items its preview shows (its cover), since the form does not load the album. */
      previewAssetIds?: string[];
      /** For an album, how many items it holds. */
      count?: number;
    };
    link?: SharedLinkResponseDto;
    /** Called once the form (or its "Link ready" step) has closed. */
    onClosed?: () => void;
  } = $props();

  const editing = $derived(!!link);
  const type = $derived(link?.type ?? target?.type ?? SharedLinkType.Individual);
  const albumId = $derived(link?.album?.id ?? target?.albumId);
  const assetCount = $derived(editing ? (link?.assets.length ?? 0) : (target?.assetIds?.length ?? 0));
  /** What the link shows, for the preview collage (`linkAssets`, SharedLinkForm.jsx:172). */
  const previewIds = $derived.by(() => {
    if (link) {
      if (link.type === SharedLinkType.Album) {
        return link.album?.albumThumbnailAssetId ? [link.album.albumThumbnailAssetId] : [];
      }
      return link.assets.map((asset) => asset.id);
    }
    return target?.type === SharedLinkType.Album ? (target.previewAssetIds ?? []) : (target?.assetIds ?? []);
  });
  const itemCount = $derived.by(() => {
    if (link) {
      return link.type === SharedLinkType.Album ? (link.album?.assetCount ?? previewIds.length) : link.assets.length;
    }
    return target?.type === SharedLinkType.Album
      ? (target.count ?? previewIds.length)
      : (target?.assetIds?.length ?? 0);
  });
  const name = $derived(target?.name ?? (link?.album ? link.album.albumName : ''));
  const ids = $props.id();
  const formId = `${ids}-form`;

  let description = $state('');
  let password = $state('');
  let showPassword = $state(false);
  let removePassword = $state(false);
  let slug = $state('');
  let allowDownload = $state(false);
  let allowUpload = $state(false);
  let showMetadata = $state(false);
  let preset = $state('never');
  let customAt = $state('');
  let error = $state('');
  let saving = $state(false);
  /** The link just created: the dialog shows the "Link ready" step while it is set. */
  let created = $state<SharedLinkResponseDto | undefined>();
  let showQr = $state(false);
  let copyStatus = $state('');
  let addressInput = $state<HTMLInputElement>();
  /** The person's own links, to say live whether a custom address is free (SharedLinkForm.jsx:126). */
  let ownLinks = $state<SharedLinkResponseDto[] | undefined>();
  /** An address the server refused on save because another link, possibly someone else's, holds it. */
  let refusedSlug = $state('');

  const SLUG_PATTERN = /^[a-z0-9-]{3,48}$/;
  /** While typing: lowercase, spaces to dashes, nothing else (`typingSlug`, SharedLinkForm.jsx:69). */
  const typingSlug = (value: string) =>
    value
      .toLowerCase()
      .replaceAll(/[\s_]+/g, '-')
      .replaceAll(/[^a-z0-9-]/g, '')
      .replaceAll(/-{2,}/g, '-')
      .slice(0, 48);
  /** On leaving the field, stray dashes at either end go too (`normalizeSlug`). */
  const normalizeSlug = (value: string) => typingSlug(value).replaceAll(/^-+|-+$/g, '');

  /** `slugAvailability` (shared-links-data.mjs:73-87), checked against the person's own links. */
  const availability = $derived.by((): 'empty' | 'invalid' | 'taken' | 'available' | 'unknown' => {
    const value = slug.trim();
    if (!value) {
      return 'empty';
    }
    // An address a link already had is left alone, even one made before these rules.
    if (link && value === link.slug) {
      return 'available';
    }
    if (!SLUG_PATTERN.test(value)) {
      return 'invalid';
    }
    if (value === refusedSlug) {
      return 'taken';
    }
    if (!ownLinks) {
      return 'unknown';
    }
    return ownLinks.some((other) => other.id !== link?.id && (other.slug === value || other.id === value))
      ? 'taken'
      : 'available';
  });
  const slugMessage = $derived(
    {
      empty: $t('frameleaf_sharing.slug_hint'),
      unknown: $t('frameleaf_sharing.slug_hint'),
      invalid: $t('frameleaf_sharing.slug_invalid'),
      taken: $t('frameleaf_sharing.slug_taken'),
      available: $t('frameleaf_sharing.slug_available'),
    }[availability],
  );

  const loadOwnLinks = async () => {
    try {
      ownLinks = (await getAllSharedLinks({})) ?? [];
    } catch {
      // Without the list the field cannot say whether an address is free; the server still checks on save.
      ownLinks = undefined;
    }
  };

  // The dialog stays open between the steps, so the "Link ready" address takes focus itself.
  $effect(() => {
    if (created && addressInput) {
      addressInput.focus();
    }
  });

  const presetLabel = (item: Preset) =>
    item.id === 'never'
      ? $t('never')
      : $t('frameleaf_sharing.expires_in', {
          values: {
            duration: new Intl.NumberFormat($locale, { style: 'unit', unit: item.unit, unitDisplay: 'long' }).format(
              item.value as number,
            ),
          },
        });

  const resetFromLink = () => {
    description = link?.description ?? '';
    password = '';
    showPassword = false;
    removePassword = false;
    slug = link?.slug ?? '';
    allowDownload = link ? link.allowDownload && link.showMetadata : false;
    allowUpload = link ? link.allowUpload : false;
    showMetadata = link ? link.showMetadata : false;
    preset = link?.expiresAt ? 'custom' : 'never';
    customAt = link?.expiresAt ? toLocalInputValue(link.expiresAt) : '';
    error = '';
    created = undefined;
    showQr = false;
    copyStatus = '';
    refusedSlug = '';
    ownLinks = undefined;
    void loadOwnLinks();
  };

  let wasOpen = false;
  $effect(() => {
    if (open && !wasOpen) {
      resetFromLink();
    }
    if (!open && wasOpen) {
      created = undefined;
      onClosed?.();
    }
    wasOpen = open;
  });

  function toLocalInputValue(iso: string): string {
    const date = new Date(iso);
    if (Number.isNaN(date.getTime())) {
      return '';
    }
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;
  }

  // Originals carry their embedded metadata, so hiding metadata turns downloads off (upstream rule).
  $effect(() => {
    if (!showMetadata && allowDownload) {
      allowDownload = false;
    }
  });

  const expiresAt = $derived.by(() => {
    if (preset === 'never') {
      return null;
    }
    if (preset === 'custom') {
      const at = Date.parse(customAt);
      return Number.isFinite(at) ? new Date(at).toISOString() : null;
    }
    const found = PRESETS.find((item) => item.id === preset);
    return found?.ms ? new Date(Date.now() + found.ms).toISOString() : null;
  });

  const expiryHint = $derived(
    expiresAt
      ? $t('frameleaf_sharing.expires_at', {
          values: { date: new Date(expiresAt).toLocaleString($locale, { dateStyle: 'medium', timeStyle: 'short' }) },
        })
      : $t('frameleaf_sharing.never_expires_hint'),
  );

  const createdUrl = $derived(created ? asUrl(created) : '');

  /* ---- AL-25: the preview aside (SharedLinkForm.jsx:137-171, 486-505) ---- */
  const hasPassword = $derived(editing ? (removePassword ? false : password ? true : !!link?.password) : !!password);
  const previewBadges = $derived(
    sharedLinkBadges({
      expiresAt,
      password: hasPassword ? 'set' : null,
      allowDownload,
      allowUpload,
      showMetadata,
    }),
  );
  const badgeIcons: Record<SharedLinkBadgeId, string> = {
    expired: mdiClockOutline,
    password: mdiLockOutline,
    download: mdiDownloadOutline,
    upload: mdiUpload,
    metadata: mdiInformationOutline,
    expiry: mdiClockOutline,
  };
  const expiresLabel = (at: string) =>
    $t('frameleaf_sharing.badge_expires', { values: { when: relativeTime(at, Date.now(), $locale ?? undefined) } });
  const badgeLabel = (id: SharedLinkBadgeId, at?: string) => {
    switch (id) {
      case 'expired': {
        return $t('expired');
      }
      case 'password': {
        return $t('password');
      }
      case 'download': {
        return $t('frameleaf_sharing.badge_downloads');
      }
      case 'upload': {
        return $t('frameleaf_sharing.badge_uploads');
      }
      case 'metadata': {
        return $t('frameleaf_sharing.badge_metadata');
      }
      case 'expiry': {
        return expiresLabel(at ?? new Date().toISOString());
      }
    }
  };
  /** The address the link will have: its custom one once free, or the one it already has. */
  const previewUrl = $derived.by(() => {
    const free = availability === 'available' && slug.trim();
    if (free) {
      // the address the new slug would give, not the link's current one
      return asUrl({ ...link, slug: free, key: link?.key ?? '', url: null } as SharedLinkResponseDto);
    }
    return link ? asUrl(link) : '';
  });
  const viewerSummary = $derived(
    [
      $t(
        showMetadata
          ? 'frameleaf_sharing.summary_items_with_metadata'
          : 'frameleaf_sharing.summary_items_without_metadata',
        { values: { count: itemCount } },
      ),
      $t(
        allowDownload
          ? allowUpload
            ? 'frameleaf_sharing.summary_download_upload'
            : 'frameleaf_sharing.summary_download_only'
          : allowUpload
            ? 'frameleaf_sharing.summary_upload_only'
            : 'frameleaf_sharing.summary_no_download',
      ),
      $t(hasPassword ? 'frameleaf_sharing.summary_password' : 'frameleaf_sharing.summary_no_password'),
      expiresAt
        ? $t('frameleaf_sharing.summary_expires', { values: { label: expiresLabel(expiresAt) } })
        : $t('frameleaf_sharing.summary_never_expires'),
    ].join(' '),
  );

  async function copyCreated() {
    try {
      await navigator.clipboard.writeText(createdUrl);
      copyStatus = $t('frameleaf_sharing.link_copied');
    } catch {
      copyStatus = $t('frameleaf_sharing.copy_unavailable');
    }
  }

  const onSlugTaken = () => {
    refusedSlug = slug.trim();
    error = $t('frameleaf_sharing.slug_taken');
  };

  async function submit(event: SubmitEvent) {
    event.preventDefault();
    if (availability === 'invalid' || availability === 'taken') {
      error = slugMessage;
      return;
    }
    // A new link must expire in the future (SharedLinkForm.jsx:185-193); an existing, already
    // expired link can still be edited without moving its date.
    if (preset === 'custom' && (!expiresAt || (!editing && Date.parse(expiresAt) <= Date.now()))) {
      error = $t('frameleaf_sharing.invalid_expiry');
      return;
    }
    saving = true;
    error = '';
    try {
      if (editing && link) {
        const success = await handleUpdateSharedLink(
          link,
          {
            description,
            slug: slug.trim() || null,
            allowDownload,
            allowUpload,
            showMetadata,
            expiresAt,
            password: removePassword ? null : password || undefined,
          },
          { onSlugTaken },
        );
        if (success) {
          open = false;
        }
      } else {
        const saved = await handleCreateSharedLink(
          {
            type,
            albumId,
            assetIds: target?.assetIds,
            description,
            slug: slug.trim() || null,
            allowDownload,
            allowUpload,
            showMetadata,
            expiresAt,
            password: password || null,
          },
          { onSlugTaken },
        );
        if (saved) {
          created = saved;
        }
      }
      // The password value never leaves this pending submission; drop it now
      // whether or not the save succeeded.
      password = '';
    } finally {
      saving = false;
    }
  }
</script>

<!-- One dialog for both steps: swapping dialogs would close the first and, with it, the whole form. -->
<Dialog
  title={created
    ? $t('frameleaf_sharing.link_ready_title')
    : editing
      ? $t('frameleaf_sharing.edit_shared_link_title')
      : $t('frameleaf_sharing.create_shared_link_title')}
  closeLabel={$t('close')}
  bind:open
>
  {#if created}
    <div class="slf-created">
      <p>
        {created.password
          ? $t('frameleaf_sharing.link_ready_body_password', { values: { name: created.description || name } })
          : $t('frameleaf_sharing.link_ready_body', { values: { name: created.description || name } })}
      </p>
      <label>
        {$t('frameleaf_sharing.link_address')}
        <input
          bind:this={addressInput}
          readonly
          value={createdUrl}
          onfocus={(event) => event.currentTarget.select()}
          aria-describedby="{ids}-created-status"
        />
      </label>
      <div class="slf-created-actions">
        <button type="button" onclick={() => void copyCreated()}>
          <Icon icon={mdiContentCopy} size="18" />
          {$t('frameleaf_sharing.copy')}
        </button>
        <button type="button" aria-pressed={showQr} onclick={() => (showQr = !showQr)}>
          <Icon icon={mdiQrcode} size="18" />
          {$t('frameleaf_sharing.qr_code')}
        </button>
        <a class="button" href={createdUrl} target="_blank" rel="noopener noreferrer">
          <Icon icon={mdiOpenInNew} size="18" />
          {$t('open')}
        </a>
      </div>
      {#if showQr}
        <div class="slf-qr">
          <QrCode
            value={createdUrl}
            label={$t('view_qr_code')}
            copyLabel={$t('copy_link')}
            downloadLabel={$t('download')}
            errorLabel={$t('frameleaf_sharing.qr_error')}
            fileName={created.slug || created.id}
            showActions={false}
          />
        </div>
      {/if}
      <span id="{ids}-created-status" class="slf-status" role="status" aria-live="polite">{copyStatus}</span>
    </div>
  {:else}
    <p class="slf-target">
      {type === SharedLinkType.Album
        ? $t('album_with_link_access')
        : $t('frameleaf_sharing.items_selected', { values: { count: assetCount } })}
      {#if name}<strong>{name}</strong>{/if}
    </p>

    <div class="slf-grid">
      <form id={formId} class="slf-fields" onsubmit={submit} novalidate>
        <label>
          {$t('description')}
          <input
            bind:value={description}
            maxlength="500"
            data-initial-focus
            placeholder={$t('frameleaf_sharing.description_placeholder')}
          />
        </label>

        <div class="slf-field">
          <label for="{ids}-password">{$t('password')}</label>
          <div class="slf-password">
            <input
              id="{ids}-password"
              type={showPassword ? 'text' : 'password'}
              autocomplete="new-password"
              bind:value={password}
              maxlength="120"
              disabled={removePassword}
              aria-describedby="{ids}-password-hint"
              placeholder={editing && link?.password && !removePassword
                ? $t('frameleaf_sharing.password_set_hint')
                : $t('frameleaf_sharing.password_placeholder')}
            />
            <button
              type="button"
              class="icon"
              aria-pressed={showPassword}
              aria-label={showPassword ? $t('hide_password') : $t('show_password')}
              title={showPassword ? $t('hide_password') : $t('show_password')}
              onclick={() => (showPassword = !showPassword)}
            >
              <Icon icon={showPassword ? mdiEyeOffOutline : mdiEyeOutline} size="18" />
            </button>
          </div>
          {#if editing && link?.password}
            <label class="slf-inline">
              <input type="checkbox" bind:checked={removePassword} />
              {$t('frameleaf_sharing.remove_password')}
            </label>
          {/if}
          <small id="{ids}-password-hint">{$t('frameleaf_sharing.password_hint')}</small>
        </div>

        <div class="slf-field">
          <label for="{ids}-slug">{$t('frameleaf_sharing.custom_address')}</label>
          <div class="slf-slug">
            <span aria-hidden="true">/s/</span>
            <input
              id="{ids}-slug"
              value={slug}
              maxlength="48"
              spellcheck="false"
              autocapitalize="off"
              placeholder={$t('frameleaf_sharing.slug_placeholder')}
              aria-describedby="{ids}-slug-hint"
              aria-invalid={availability === 'invalid' || availability === 'taken'}
              oninput={(event) => {
                slug = typingSlug(event.currentTarget.value);
                event.currentTarget.value = slug;
              }}
              onblur={() => (slug = normalizeSlug(slug))}
            />
          </div>
          <small id="{ids}-slug-hint" class="slf-slug-status" data-status={availability} role="status">
            {slugMessage}
          </small>
          {#if editing && link && (slug.trim() || null) !== (link.slug || null)}
            <p class="slf-warning" role="status">{$t('frameleaf_sharing.slug_change_warning')}</p>
          {/if}
        </div>

        <div class="slf-toggles">
          <label class="slf-toggle">
            <span>
              <strong>{$t('frameleaf_sharing.allow_download')}</strong>
              <small id="{ids}-download-hint">
                {showMetadata
                  ? $t('frameleaf_sharing.allow_download_description')
                  : $t('frameleaf_sharing.download_needs_metadata')}
              </small>
            </span>
            <input
              type="checkbox"
              role="switch"
              class="slf-switch"
              bind:checked={allowDownload}
              disabled={!showMetadata}
              aria-describedby="{ids}-download-hint"
            />
          </label>
          <label class="slf-toggle">
            <span>
              <strong>{$t('frameleaf_sharing.allow_upload')}</strong>
              <small>{$t('frameleaf_sharing.allow_upload_description')}</small>
            </span>
            <input type="checkbox" role="switch" class="slf-switch" bind:checked={allowUpload} />
          </label>
          <label class="slf-toggle">
            <span>
              <strong>{$t('show_metadata')}</strong>
              <small>{$t('frameleaf_sharing.show_metadata_description')}</small>
            </span>
            <input type="checkbox" role="switch" class="slf-switch" bind:checked={showMetadata} />
          </label>
        </div>

        <div class="slf-expiry">
          <label>
            {$t('frameleaf_sharing.expires')}
            <select bind:value={preset}>
              {#each PRESETS as item (item.id)}
                <option value={item.id}>{presetLabel(item)}</option>
              {/each}
              <option value="custom">{$t('frameleaf_sharing.custom_expiry')}</option>
            </select>
          </label>
          {#if preset === 'custom'}
            <label>
              {$t('frameleaf_sharing.expiry_date_time')}
              <input type="datetime-local" bind:value={customAt} min={toLocalInputValue(new Date().toISOString())} />
            </label>
          {/if}
        </div>
        <small>{expiryHint}</small>

        {#if error}
          <p class="slf-error" role="alert">{error}</p>
        {/if}

        {#if editing && link}
          <div class="slf-qr">
            <QrCode
              value={asUrl(link)}
              label={$t('view_qr_code')}
              copyLabel={$t('copy_link')}
              downloadLabel={$t('download')}
              errorLabel={$t('frameleaf_sharing.qr_error')}
              fileName={link.slug || link.id}
              showActions={true}
            />
          </div>
        {/if}
      </form>

      <aside class="slf-preview" aria-label={$t('frameleaf_sharing.link_preview')}>
        <AssetCollage ids={previewIds} count={itemCount} />
        <div class="slf-preview-body">
          <strong>{description.trim() || name}</strong>
          <small>
            {type === SharedLinkType.Album
              ? $t('frameleaf_sharing.preview_album', { values: { name } })
              : $t('frameleaf_sharing.preview_individual')} · {$t('frameleaf_sharing.individual_items', {
              values: { count: itemCount },
            })}
          </small>
          <p class="slf-url">
            <Icon icon={mdiLinkVariant} size="16" aria-hidden={true} />
            {#if previewUrl}
              <span>{previewUrl}</span>
            {:else}
              <span class="slf-muted">{$t('frameleaf_sharing.preview_address_pending')}</span>
            {/if}
          </p>
          <ul class="slf-badges" aria-label={$t('frameleaf_sharing.link_details')}>
            {#each previewBadges as badge (badge.id)}
              <li class="slf-badge" data-tone={badge.tone}>
                <Icon icon={badgeIcons[badge.id]} size="14" aria-hidden={true} />
                {badgeLabel(badge.id, badge.at)}
              </li>
            {/each}
          </ul>
          <p class="slf-summary">{viewerSummary}</p>
        </div>
      </aside>
    </div>
  {/if}
  {#snippet actions()}
    {#if created}
      <button type="button" class="primary" onclick={() => (open = false)}>{$t('done')}</button>
    {:else}
      <button type="button" onclick={() => (open = false)}>{$t('cancel')}</button>
      <button type="submit" form={formId} class="primary" disabled={saving}>
        {editing ? $t('save') : $t('create_link')}
      </button>
    {/if}
  {/snippet}
</Dialog>

<style>
  .slf-grid {
    display: grid;
    grid-template-columns: minmax(0, 1fr) minmax(220px, 280px);
    gap: 1.25rem;
    align-items: start;
  }
  @media (max-width: 720px) {
    .slf-grid {
      grid-template-columns: minmax(0, 1fr);
    }
  }
  .slf-preview {
    display: flex;
    flex-direction: column;
    background: var(--fl-raised);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius);
    overflow: hidden;
  }
  .slf-preview-body {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding: 0.75rem;
    min-width: 0;
  }
  .slf-preview-body strong {
    overflow-wrap: anywhere;
  }
  .slf-url {
    display: flex;
    align-items: center;
    gap: 0.375rem;
    margin: 0;
    font-size: var(--fl-font-micro);
    overflow-wrap: anywhere;
  }
  .slf-muted {
    color: var(--fl-muted);
  }
  .slf-badges {
    list-style: none;
    margin: 0;
    padding: 0;
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
  }
  .slf-badge {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    font-size: var(--fl-font-micro);
    line-height: 1;
    color: var(--fl-muted);
    background: var(--fl-bg, var(--fl-surface));
    border-radius: var(--fl-radius-pill);
    padding: 5px 9px;
  }
  .slf-badge[data-tone='danger'] {
    color: var(--fl-danger);
    background: color-mix(in srgb, var(--fl-danger), transparent 86%);
  }
  .slf-badge[data-tone='info'] {
    color: var(--fl-teal);
    background: color-mix(in srgb, var(--fl-teal), transparent 86%);
  }
  .slf-summary {
    margin: 0;
    color: var(--fl-muted);
    font-size: 0.8125rem;
  }
  .slf-slug-status[data-status='available'] {
    color: var(--fl-teal);
  }
  .slf-slug-status[data-status='invalid'],
  .slf-slug-status[data-status='taken'] {
    color: var(--fl-danger);
  }
  .slf-target {
    color: var(--fl-muted);
    font-size: 0.875rem;
  }
  .slf-fields {
    display: flex;
    flex-direction: column;
    gap: 1rem;
  }
  label {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    font-size: 0.875rem;
  }
  input,
  select {
    background: var(--fl-raised);
    color: var(--fl-text);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius);
    padding: 0.5rem;
  }
  .slf-field {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    font-size: 0.875rem;
  }
  .slf-password {
    display: flex;
    gap: 0.5rem;
  }
  .slf-password input {
    flex: 1;
  }
  .slf-password button {
    background: var(--fl-raised);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius);
    color: var(--fl-text);
  }
  .slf-inline {
    flex-direction: row;
    align-items: center;
    gap: 0.5rem;
  }
  small {
    color: var(--fl-muted);
  }
  .slf-warning {
    color: var(--fl-accent);
    font-size: 0.8125rem;
  }
  .slf-toggles {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .slf-toggle {
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    gap: 1rem;
  }
  .slf-expiry {
    display: flex;
    flex-wrap: wrap;
    gap: 1rem;
  }
  .slf-error {
    color: var(--fl-accent);
  }
  .slf-qr {
    display: flex;
    justify-content: center;
    padding: 0.5rem 0;
  }
  .slf-toggle > span {
    display: flex;
    flex-direction: column;
    gap: 0.125rem;
  }
  .slf-slug {
    display: flex;
    align-items: center;
    gap: 0.25rem;
  }
  .slf-slug span {
    color: var(--fl-muted);
    font-family: var(--fl-font-mono, monospace);
  }
  .slf-slug input {
    flex: 1;
  }
  .slf-password button.icon {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 44px;
  }
  .slf-created {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
  }
  .slf-created p {
    margin: 0;
  }
  .slf-created-actions {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
  .slf-created-actions button,
  .slf-created-actions .button,
  button.primary,
  button[type='button']:not(.icon) {
    display: inline-flex;
    align-items: center;
    gap: 0.375rem;
    min-height: 40px;
    padding: 0 1rem;
    background: var(--fl-raised);
    color: var(--fl-text);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius);
    text-decoration: none;
  }
  .slf-created-actions button[aria-pressed='true'] {
    border-color: var(--fl-accent);
  }
  button.primary {
    background: var(--fl-accent);
    color: var(--fl-accent-text);
    border-color: var(--fl-accent);
  }
  .slf-status {
    color: var(--fl-muted);
    font-size: 0.875rem;
    min-height: 1.25rem;
  }
</style>

// design/frameleaf/template/src/SharedLinkForm.jsx
import React, { useEffect, useId, useMemo, useRef, useState } from "react";
import { Button, Dialog } from "./App";
import { Icon } from "./Icon";
import { QrCode, copyText } from "./QrCode";
import {
  EXPIRY_PRESETS,
  absoluteLinkUrl,
  expiryFromPreset,
  expiryLabel,
  fromLocalInputValue,
  linkAssets,
  linkBadges,
  linkUrl,
  normalizeSlug,
  slugAvailability,
  toLocalInputValue,
} from "./shared-links-data.mjs";
import "./sharing.css";

/** Current time that refreshes on an interval, for countdowns. */
export function useNow(interval = 60_000) {
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), interval);
    return () => clearInterval(id);
  }, [interval]);
  return now;
}

/** Cover collage of up to four items; placeholders render as icon tiles. */
export function AssetCollage({ items = [], previews = {}, className = "" }) {
  const shown = items.slice(0, 4);
  return (
    <div className={`sl-collage ${className}`} data-count={shown.length} aria-hidden="true">
      {shown.length ? (
        shown.map((item) => {
          const src = item.placeholder ? previews[item.name] : item.image;
          return src ? (
            <img key={item.id} src={src} alt="" loading="lazy" />
          ) : (
            <span key={item.id} className="sl-collage-blank">
              <Icon name={item.type === "video" ? "mdiVideoOutline" : "mdiImageOutline"} />
            </span>
          );
        })
      ) : (
        <span className="sl-collage-blank">
          <Icon name="mdiImageMultipleOutline" />
        </span>
      )}
      {items.length > 4 && <span className="sl-collage-more">+{items.length - 4}</span>}
    </div>
  );
}

export function Badges({ badges, className = "" }) {
  return (
    <ul className={`sl-badges ${className}`} aria-label="Link details">
      {badges.map((badge) => (
        <li key={badge.id} className="sl-badge" data-tone={badge.tone || "neutral"}>
          {badge.icon && <Icon name={badge.icon} size={14} />}
          {badge.label}
        </li>
      ))}
    </ul>
  );
}

const typingSlug = (value) =>
  String(value)
    .toLowerCase()
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-{2,}/g, "-")
    .slice(0, 48);

function originBase() {
  return typeof location === "object" && location
    ? `${location.origin}${location.pathname}`
    : "https://frameleaf.local/";
}

/**
 * Create or edit a shared link.
 * props: { link|null, target {type, albumId|assetIds, name}, links, assets,
 *          onSave(input) -> saved link, onClose(), onOpen(link) }
 */
export function SharedLinkForm({
  link = null,
  target,
  links = [],
  assets = [],
  onSave,
  onClose,
  onOpen,
}) {
  const editing = !!link;
  const now = useNow();
  const ids = useId();
  const formId = `${ids}-form`;
  const [description, setDescription] = useState(link?.description ?? "");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [removePassword, setRemovePassword] = useState(false);
  const [slug, setSlug] = useState(link?.slug ?? "");
  const [allowDownload, setAllowDownload] = useState(link ? link.allowDownload : true);
  const [allowUpload, setAllowUpload] = useState(link ? link.allowUpload : false);
  const [showMetadata, setShowMetadata] = useState(link ? link.showMetadata : false);
  const [preset, setPreset] = useState(link?.expiresAt ? "custom" : "never");
  const [customAt, setCustomAt] = useState(
    link?.expiresAt ? toLocalInputValue(link.expiresAt) : "",
  );
  const [error, setError] = useState("");
  const [created, setCreated] = useState(null);
  const [showQr, setShowQr] = useState(false);
  const [status, setStatus] = useState("");
  const statusTimer = useRef(null);
  useEffect(() => () => clearTimeout(statusTimer.current), []);

  const type = link?.type ?? target?.type ?? "album";
  const albumId = link?.albumId ?? target?.albumId ?? null;
  const assetIds = link?.assetIds ?? target?.assetIds ?? [];
  const name =
    target?.name ||
    (type === "album" ? albumId : `${assetIds.length} ${assetIds.length === 1 ? "item" : "items"}`);
  const availability = slugAvailability(slug, links, link?.id);
  const slugChanged = editing && (slug.trim() || null) !== (link.slug || null);
  const expiresAt =
    preset === "custom" ? fromLocalInputValue(customAt) : expiryFromPreset(preset, now);
  const hasPassword = editing
    ? removePassword
      ? false
      : password
        ? true
        : link.hasPassword
    : !!password;
  const preview = useMemo(
    () => ({
      id: link?.id ?? "new-link",
      type,
      albumId,
      assetIds,
      description: description.trim(),
      slug: availability.status === "available" ? slug.trim() : null,
      hasPassword,
      allowDownload,
      allowUpload,
      showMetadata,
      expiresAt,
      views: link?.views ?? 0,
      uploads: link?.uploads ?? [],
    }),
    [
      link,
      type,
      albumId,
      assetIds,
      description,
      availability.status,
      slug,
      hasPassword,
      allowDownload,
      allowUpload,
      showMetadata,
      expiresAt,
    ],
  );
  const items = useMemo(() => linkAssets(preview, assets), [preview, assets]);
  const key = created
    ? created.slug || created.id
    : preview.slug || (editing ? link.id : null);
  const url = key ? `${originBase()}?screen=public&link=${encodeURIComponent(key)}` : null;
  const announce = (message) => {
    setStatus(message);
    clearTimeout(statusTimer.current);
    statusTimer.current = setTimeout(() => setStatus(""), 2500);
  };

  function submit(event) {
    event?.preventDefault();
    if (slug.trim() && availability.status !== "available") {
      setError(availability.message);
      return;
    }
    if (preset === "custom") {
      if (!expiresAt) {
        setError("Choose a date and time for the link to expire.");
        return;
      }
      if (Date.parse(expiresAt) <= now) {
        setError("Choose an expiry in the future.");
        return;
      }
    }
    const input = {
      type,
      albumId,
      assetIds,
      description: description.trim(),
      slug: slug.trim() || null,
      allowDownload,
      allowUpload,
      showMetadata,
      expiresAt,
    };
    if (editing) {
      if (removePassword) input.password = null;
      else if (password) input.password = password;
    } else input.password = password || null;
    let saved;
    try {
      saved = onSave?.(input);
    } catch (failure) {
      setError(failure?.message || "The link could not be saved.");
      return;
    }
    setError("");
    if (editing) {
      onClose?.();
      return;
    }
    setCreated(saved && typeof saved === "object" ? saved : { ...preview, id: "new-link" });
  }

  const viewerSummary = [
    `Viewers see ${items.length} ${items.length === 1 ? "item" : "items"}${
      showMetadata ? " with camera and location details" : " without camera or location details"
    }.`,
    allowDownload ? "They can download originals" : "Downloads are off",
    allowUpload ? "and can add their own photos." : ".",
    hasPassword ? "A password is required." : "No password is needed.",
    expiresAt ? `${expiryLabel(preview, now)}.` : "The link never expires.",
  ]
    .join(" ")
    .replace(/ \./g, ".");

  if (created)
    return (
      <Dialog
        title="Link ready"
        close={onClose}
        actions={
          <Button primary onClick={onClose}>
            Done
          </Button>
        }
      >
        <div className="slf-created">
          <p>
            Anyone with this address can view <strong>{created.description || name}</strong>
            {created.hasPassword ? " after entering the password" : ""}.
          </p>
          <label>
            Link address
            <input
              readOnly
              value={url}
              data-initial-focus
              onFocus={(event) => event.target.select()}
              aria-describedby={`${ids}-created-status`}
            />
          </label>
          <div className="slf-created-actions">
            <Button
              icon="mdiContentCopy"
              onClick={async () => {
                announce((await copyText(url)) ? "Link copied." : "Copying is not available here.");
              }}
            >
              Copy
            </Button>
            <Button
              icon="mdiQrcode"
              active={showQr}
              aria-pressed={showQr}
              onClick={() => setShowQr(!showQr)}
            >
              QR code
            </Button>
            <Button
              icon="mdiOpenInNew"
              onClick={() =>
                onOpen ? onOpen(created) : window.open(linkUrl(created), "_blank", "noopener")
              }
            >
              Open
            </Button>
          </div>
          {showQr && (
            <QrCode
              value={url}
              label="Shared link QR code"
              fileName={created.slug || created.id}
              showActions={false}
            />
          )}
          <Badges badges={linkBadges(created, now)} />
          <span id={`${ids}-created-status`} className="slf-status" role="status" aria-live="polite">
            {status}
          </span>
        </div>
      </Dialog>
    );

  return (
    <Dialog
      title={editing ? "Edit shared link" : "Create shared link"}
      close={onClose}
      wide
      actions={
        <>
          <Button onClick={onClose}>Cancel</Button>
          <Button primary type="submit" form={formId}>
            {editing ? "Save" : "Create link"}
          </Button>
        </>
      }
    >
      <div className="slf-grid">
        <form id={formId} className="slf-fields" onSubmit={submit} noValidate>
          <label>
            Description
            <input
              data-initial-focus
              value={description}
              maxLength={500}
              placeholder="Add a title viewers will see"
              onChange={(event) => setDescription(event.target.value)}
            />
          </label>

          <div className="slf-field">
            <label htmlFor={`${ids}-password`}>Password</label>
            <div className="slf-password">
              <input
                id={`${ids}-password`}
                type={showPassword ? "text" : "password"}
                autoComplete="new-password"
                value={password}
                maxLength={120}
                disabled={removePassword}
                placeholder={
                  editing && link.hasPassword && !removePassword
                    ? "Password set · enter a new one to replace it"
                    : "Optional"
                }
                onChange={(event) => setPassword(event.target.value)}
                aria-describedby={`${ids}-password-hint`}
              />
              <Button
                type="button"
                icon={showPassword ? "mdiEyeOffOutline" : "mdiEyeOutline"}
                aria-label={showPassword ? "Hide password" : "Show password"}
                aria-pressed={showPassword}
                onClick={() => setShowPassword(!showPassword)}
              />
            </div>
            {editing && link.hasPassword && (
              <label className="slf-inline">
                <input
                  type="checkbox"
                  checked={removePassword}
                  onChange={(event) => setRemovePassword(event.target.checked)}
                />
                Remove password
              </label>
            )}
            <small id={`${ids}-password-hint`} className="slf-hint">
              Viewers enter this before seeing anything.
            </small>
          </div>

          <div className="slf-field">
            <label htmlFor={`${ids}-slug`}>Custom address</label>
            <div className="slf-slug">
              <span aria-hidden="true">?link=</span>
              <input
                id={`${ids}-slug`}
                value={slug}
                maxLength={48}
                spellCheck={false}
                autoCapitalize="off"
                placeholder="summer-trip"
                onChange={(event) => setSlug(typingSlug(event.target.value))}
                onBlur={() => setSlug(normalizeSlug(slug))}
                aria-describedby={`${ids}-slug-hint`}
                aria-invalid={["invalid", "taken"].includes(availability.status)}
              />
            </div>
            <small
              id={`${ids}-slug-hint`}
              className="slf-hint"
              data-status={availability.status}
              role="status"
            >
              {availability.message}
            </small>
            {slugChanged && (
              <p className="slf-warning" role="status">
                <Icon name="mdiAlertOutline" size={16} />
                Changing the address breaks the previous link. Anyone using the old
                address will see “This link is not available”.
              </p>
            )}
          </div>

          <div className="slf-toggles">
            <label className="slf-toggle">
              <span>
                <strong>Allow download</strong>
                <small>Viewers can save originals, one at a time or as an archive.</small>
              </span>
              <input
                type="checkbox"
                role="switch"
                className="slf-switch"
                checked={allowDownload}
                onChange={(event) => setAllowDownload(event.target.checked)}
              />
            </label>
            <label className="slf-toggle">
              <span>
                <strong>Allow upload</strong>
                <small>Viewers can add photos and videos to this share.</small>
              </span>
              <input
                type="checkbox"
                role="switch"
                className="slf-switch"
                checked={allowUpload}
                onChange={(event) => setAllowUpload(event.target.checked)}
              />
            </label>
            <label className="slf-toggle">
              <span>
                <strong>Show metadata</strong>
                <small>Camera, exposure, capture time and location (EXIF).</small>
              </span>
              <input
                type="checkbox"
                role="switch"
                className="slf-switch"
                checked={showMetadata}
                onChange={(event) => setShowMetadata(event.target.checked)}
              />
            </label>
          </div>

          <div className="field-pair slf-expiry">
            <label>
              Expires
              <select value={preset} onChange={(event) => setPreset(event.target.value)}>
                {EXPIRY_PRESETS.map((entry) => (
                  <option key={entry.id} value={entry.id}>
                    {entry.id === "never" ? "Never" : `In ${entry.label}`}
                  </option>
                ))}
                <option value="custom">Custom date and time</option>
              </select>
            </label>
            {preset === "custom" && (
              <label>
                Expiry date and time
                <input
                  type="datetime-local"
                  value={customAt}
                  min={toLocalInputValue(new Date(now).toISOString())}
                  onChange={(event) => setCustomAt(event.target.value)}
                />
              </label>
            )}
          </div>
          <small className="slf-hint">
            {expiresAt
              ? `${expiryLabel(preview, now)} · ${new Date(expiresAt).toLocaleString()}`
              : "The link stays open until you delete it."}
          </small>
          {error && (
            <p className="slf-error" role="alert">
              <Icon name="mdiAlertCircleOutline" size={16} />
              {error}
            </p>
          )}
        </form>

        <aside className="slf-preview" aria-label="Link preview">
          <AssetCollage items={items} />
          <div className="slf-preview-body">
            <strong>{description.trim() || name}</strong>
            <small>
              {type === "album" ? `Album · ${name}` : "Individual items"} · {items.length}{" "}
              {items.length === 1 ? "item" : "items"}
            </small>
            <p className="slf-url">
              <Icon name="mdiLinkVariant" size={16} />
              {url ? (
                <span>{url}</span>
              ) : (
                <span className="muted">Address is generated when you create the link</span>
              )}
            </p>
            <Badges badges={linkBadges(preview, now)} />
            <p className="slf-summary">{viewerSummary}</p>
          </div>
        </aside>
      </div>
    </Dialog>
  );
}
