// web/src/lib/components/frameleaf/WorkflowDesigner.svelte
<script lang="ts">
  /**
   * The workflow designer (FL-82), ported from the design template's `WorkflowDesigner.jsx`: Steps,
   * Validation, History and JSON over one draft of the complete definition.
   *
   * Methods, triggers and templates are the ones the server's installed, enabled plugins provide;
   * nothing is invented. A step whose method is not installed, an unavailable trigger, unknown
   * parameters and additional fields all stay in the draft and are saved and exported unchanged. The
   * server refuses to enable or run what cannot run, and the draft stays open when a save fails.
   * History is the server's real run log: attempts, failures and manual retry.
   */
  import Button from '$lib/components/frameleaf/Button.svelte';
  import Dialog from '$lib/components/frameleaf/Dialog.svelte';
  import WorkflowParameter, { type ReferenceOption } from '$lib/components/frameleaf/WorkflowParameter.svelte';
  import '$lib/frameleaf/workflow-designer.css';
  import {
    cloneJson,
    draftFromDocument,
    draftToCreateDto,
    draftToDocument,
    draftToUpdateDto,
    exportDraft,
    exportFileName,
    findMethod,
    isFilterMethod,
    methodSchema,
    parseWorkflowDefinition,
    schemaDefaults,
    WORKFLOW_LIMITS,
    previewWorkflow,
    workflowProblems,
    type WorkflowDraft,
    type WorkflowDraftStep,
  } from '$lib/frameleaf/workflows';
  import { Route } from '$lib/route';
  import { downloadJson } from '$lib/utils';
  import { getServerErrorMessage } from '$lib/utils/handle-error';
  import {
    createWorkflow,
    deleteWorkflow,
    getWorkflowLogs,
    retryWorkflowRun,
    updateWorkflow,
    WorkflowResult,
    WorkflowRunErrorCode,
    type PluginMethodResponseDto,
    type PluginTemplateResponseDto,
    type WorkflowLogEntryDto,
    type WorkflowResponseDto,
    type WorkflowTriggerResponseDto,
  } from '@frameleaf/sdk';
  import { DateTime } from 'luxon';
  import { t, type Translations } from 'svelte-i18n';

  type Tab = 'steps' | 'validation' | 'history' | 'json';

  let {
    open = $bindable(false),
    workflow,
    initial,
    methods,
    triggers,
    templates,
    references = {},
    onSaved,
    onDeleted,
  }: {
    open?: boolean;
    /** The stored workflow, or none for a new or imported one. */
    workflow?: WorkflowResponseDto;
    initial: WorkflowDraft;
    methods: PluginMethodResponseDto[];
    triggers: WorkflowTriggerResponseDto[];
    templates: PluginTemplateResponseDto[];
    references?: Record<string, ReferenceOption[]>;
    onSaved: (workflow: WorkflowResponseDto) => void;
    onDeleted: (id: string) => void;
  } = $props();

  // svelte-ignore state_referenced_locally
  let draft = $state<WorkflowDraft>(cloneJson(initial));
  // svelte-ignore state_referenced_locally
  const saved = JSON.stringify(initial);
  let tab = $state<Tab>('steps');
  let active = $state(0);
  // svelte-ignore state_referenced_locally
  let method = $state(methods[0]?.key ?? '');
  let template = $state('');
  let error = $state('');
  let raw = $state('');
  let parameterJson = $state<string | null>(null);
  let validation = $state<ReturnType<typeof previewWorkflow> | null>(null);
  let deleting = $state(false);
  let saving = $state(false);

  const document = $derived(JSON.stringify(draftToDocument(draft), null, 2));
  const problems = $derived(workflowProblems(draft, methods, triggers));
  const persistError = $derived(
    draft.enabled && problems.length > 0
      ? $t('frameleaf_workflows.pause_before_saving', { values: { problem: problems[0].message } })
      : '',
  );
  const dirty = $derived(JSON.stringify(draft) !== saved);
  const selected = $derived<WorkflowDraftStep | undefined>(draft.steps[active]);
  const parametersPending = $derived(
    parameterJson !== null && parameterJson !== JSON.stringify(selected?.config ?? null, null, 2),
  );
  const definition = $derived(selected ? findMethod(methods, selected.method) : undefined);
  const jsonPending = $derived(tab === 'json' && raw !== document);
  const knownTrigger = $derived(triggers.some((item) => item.trigger === draft.trigger));
  const triggerLabel = (trigger: string) => {
    const key = `frameleaf_workflows.trigger_${trigger}`;
    const label = $t(key as Translations);
    return label === key ? trigger : label;
  };

  const update = (next: WorkflowDraft) => {
    draft = next;
    error = '';
    validation = null;
  };

  const updateStep = (next: WorkflowDraftStep) =>
    update({ ...draft, steps: draft.steps.map((step, index) => (index === active ? next : step)) });

  const move = (index: number, offset: number) => {
    const target = index + offset;
    if (target < 0 || target >= draft.steps.length) {
      return;
    }
    const steps = [...draft.steps];
    const [moved] = steps.splice(index, 1);
    steps.splice(target, 0, moved);
    update({ ...draft, steps });
    active = target;
  };

  const removeStep = (index: number) => {
    update({ ...draft, steps: draft.steps.filter((_, i) => i !== index) });
    active = Math.max(0, Math.min(active, draft.steps.length - 1));
    parameterJson = null;
  };

  const addStep = () => {
    const chosen = methods.find((item) => item.key === method);
    if (!chosen || draft.steps.length >= WORKFLOW_LIMITS.steps) {
      return;
    }
    const config = schemaDefaults(methodSchema(chosen)) as Record<string, unknown>;
    update({
      ...draft,
      steps: [...draft.steps, { method: chosen.key, config, enabled: true, extra: {}, storedSecrets: [] }],
    });
    active = draft.steps.length - 1;
  };

  const applyTemplate = () => {
    const chosen = templates.find((item) => item.key === template);
    if (!chosen) {
      return;
    }
    update({
      ...draft,
      trigger: chosen.trigger,
      name: draft.name || chosen.title,
      description: draft.description || chosen.description,
      enabled: false,
      steps: chosen.steps.map((step) => ({
        method: step.method,
        config: cloneJson(step.config),
        enabled: step.enabled !== false,
        extra: {},
        storedSecrets: [],
      })),
    });
    active = 0;
    template = '';
  };

  const chooseTab = (next: Tab) => {
    error = '';
    if (next === 'json') {
      raw = document;
    } else if (next === 'history') {
      void loadLogs(true);
    }
    parameterJson = null;
    tab = next;
  };

  const applyJson = () => {
    try {
      update(draftFromDocument(raw, draft));
      raw = document;
    } catch (error_) {
      error = (error_ as Error).message;
    }
  };

  const applyParameters = () => {
    if (!selected || parameterJson === null) {
      return;
    }
    try {
      const config = JSON.parse(parameterJson) as Record<string, unknown> | null;
      const next = { ...selected, config };
      parseWorkflowDefinition({
        ...draftToDocument({ ...draft, steps: draft.steps.map((step, i) => (i === active ? next : step)) }),
      });
      updateStep(next);
      parameterJson = null;
    } catch (error_) {
      error = (error_ as Error).message;
    }
  };

  const save = async () => {
    if (persistError || saving) {
      error = persistError;
      return;
    }
    saving = true;
    try {
      const response = workflow
        ? await updateWorkflow({ id: workflow.id, workflowUpdateDto: draftToUpdateDto(draft) })
        : await createWorkflow({ workflowCreateDto: draftToCreateDto(draft) });
      onSaved(response);
      open = false;
    } catch (error_) {
      // the draft stays open with everything in it
      error = getServerErrorMessage(error_) ?? $t('errors.unable_to_update_workflow');
    } finally {
      saving = false;
    }
  };

  const remove = async () => {
    if (!workflow) {
      open = false;
      return;
    }
    try {
      await deleteWorkflow({ id: workflow.id });
      onDeleted(workflow.id);
      open = false;
    } catch (error_) {
      error = getServerErrorMessage(error_) ?? $t('errors.unable_to_delete_workflow');
    }
  };

  const cancel = () => {
    if ((!dirty && !jsonPending && !parametersPending) || confirm($t('frameleaf_workflows.discard_prompt'))) {
      open = false;
    }
  };

  // -------------------------------------------------------------------------------------------------
  // History

  let logs = $state<WorkflowLogEntryDto[]>([]);
  let logFilter = $state<WorkflowResult | ''>('');
  let logsLoading = $state(false);
  let logsMore = $state(false);
  let notice = $state('');
  const LOG_PAGE = 50;

  const loadLogs = async (reset: boolean) => {
    if (!workflow || logsLoading) {
      return;
    }
    logsLoading = true;
    try {
      const before = reset ? undefined : logs.at(-1)?.at;
      const page = await getWorkflowLogs({ id: workflow.id, limit: LOG_PAGE, before, result: logFilter || undefined });
      logs = reset ? page : [...logs, ...page];
      logsMore = page.length === LOG_PAGE;
    } catch (error_) {
      error = getServerErrorMessage(error_) ?? $t('errors.something_went_wrong');
    } finally {
      logsLoading = false;
    }
  };

  const retry = async (entry: WorkflowLogEntryDto) => {
    if (!workflow) {
      return;
    }
    try {
      await retryWorkflowRun({ id: workflow.id, runId: entry.runId });
      notice = $t('frameleaf_workflows.retry_queued');
    } catch (error_) {
      error = getServerErrorMessage(error_) ?? $t('errors.something_went_wrong');
    }
  };

  const attemptLabel = (attempt: number) =>
    attempt === 0
      ? $t('frameleaf_workflows.attempt_first')
      : attempt === 1
        ? $t('frameleaf_workflows.attempt_retry')
        : $t('frameleaf_workflows.attempt_manual', { values: { number: attempt } });

  const resultLabel = (entry: WorkflowLogEntryDto) => {
    if (entry.errorCode === WorkflowRunErrorCode.Unsupported) {
      return $t('frameleaf_workflows.not_run');
    }
    const label = {
      [WorkflowResult.Completed]: $t('frameleaf_workflows.result_completed'),
      [WorkflowResult.Halted]: $t('frameleaf_workflows.result_halted'),
      [WorkflowResult.Error]: $t('frameleaf_workflows.result_error'),
    }[entry.result];
    return entry.lastStep
      ? `${label} ${$t('frameleaf_workflows.stopped_at_step', { values: { step: entry.lastStep.index + 1 } })}`
      : label;
  };
</script>

<Dialog
  title={draft.name || $t('frameleaf_workflows.new_workflow')}
  closeLabel={$t('close')}
  onRequestClose={cancel}
  wide
  bind:open
>
  <div class="workflow-designer">
    <div class="wd-tabs" role="group" aria-label={$t('frameleaf_workflows.tabs_label')}>
      {#each [['steps', 'tab_steps'], ['validation', 'tab_validation'], ['history', 'tab_history'], ['json', 'tab_json']] as const as [id, key] (id)}
        <Button pressed={tab === id} onclick={() => chooseTab(id)}>{$t(`frameleaf_workflows.${key}`)}</Button>
      {/each}
    </div>

    {#if error}<p role="alert" class="wd-error">{error}</p>{/if}
    {#if persistError}<p class="wd-message">{persistError}</p>{/if}

    {#if tab === 'steps'}
      <div class="wd-meta">
        <label class="wd-field">
          {$t('frameleaf_workflows.name')}
          <input
            value={draft.name ?? ''}
            maxlength={300}
            oninput={(event) => update({ ...draft, name: event.currentTarget.value || null })}
          />
        </label>
        <label class="wd-field">
          {$t('frameleaf_workflows.trigger')}
          <select value={draft.trigger} onchange={(event) => update({ ...draft, trigger: event.currentTarget.value })}>
            {#if !knownTrigger}
              <option value={draft.trigger}>
                {$t('frameleaf_workflows.trigger_unavailable', { values: { trigger: draft.trigger } })}
              </option>
            {/if}
            {#each triggers as item (item.trigger)}
              <option value={item.trigger}>{triggerLabel(item.trigger)}</option>
            {/each}
          </select>
        </label>
        <label class="wd-field wd-description">
          {$t('frameleaf_workflows.description')}
          <textarea
            rows={2}
            value={draft.description ?? ''}
            oninput={(event) => update({ ...draft, description: event.currentTarget.value || null })}></textarea>
        </label>
      </div>

      <div class="wd-switches">
        <label>
          <input
            type="checkbox"
            checked={draft.enabled}
            disabled={!draft.enabled && problems.length > 0}
            onchange={(event) => update({ ...draft, enabled: event.currentTarget.checked })}
          />
          {$t('frameleaf_workflows.enable_workflow')}
        </label>
        <label>
          <input
            type="checkbox"
            checked={draft.logging}
            onchange={(event) => update({ ...draft, logging: event.currentTarget.checked })}
          />
          {$t('frameleaf_workflows.keep_history')}
        </label>
      </div>

      {#if templates.length > 0}
        <div class="wd-template">
          <label>
            {$t('frameleaf_workflows.template')}
            <select bind:value={template}>
              <option value="">{$t('frameleaf_workflows.choose_template')}</option>
              {#each templates as item (item.key)}
                <option value={item.key}>{item.title}</option>
              {/each}
            </select>
          </label>
          {#if template}
            <p>{templates.find((item) => item.key === template)?.description}</p>
            <Button onclick={applyTemplate}>{$t('frameleaf_workflows.replace_with_template')}</Button>
          {/if}
        </div>
      {/if}

      <div class="wd-workspace">
        <div class="wd-steps">
          <h3>{$t('frameleaf_workflows.ordered_steps')}</h3>
          <ol>
            {#each draft.steps as step, index (index)}
              {@const stepMethod = findMethod(methods, step.method)}
              <li class:selected={index === active} class:problem={problems.some((problem) => problem.step === index)}>
                <button
                  type="button"
                  class="wd-step-select"
                  aria-current={index === active ? 'step' : undefined}
                  onclick={() => {
                    active = index;
                    parameterJson = null;
                  }}
                >
                  <strong>
                    {$t('frameleaf_workflows.step_title', {
                      values: {
                        index: index + 1,
                        title: stepMethod?.title ?? $t('frameleaf_workflows.unavailable_method'),
                      },
                    })}
                  </strong>
                  <small>
                    {step.enabled
                      ? isFilterMethod(stepMethod)
                        ? $t('frameleaf_workflows.step_filter')
                        : $t('frameleaf_workflows.step_action')
                      : $t('frameleaf_workflows.step_disabled')}
                  </small>
                </button>
                <div class="wd-step-actions">
                  <Button
                    disabled={index === 0}
                    label={$t('frameleaf_workflows.move_earlier', { values: { index: index + 1 } })}
                    onclick={() => move(index, -1)}>↑</Button
                  >
                  <Button
                    disabled={index === draft.steps.length - 1}
                    label={$t('frameleaf_workflows.move_later', { values: { index: index + 1 } })}
                    onclick={() => move(index, 1)}>↓</Button
                  >
                  <Button
                    label={$t('frameleaf_workflows.remove_step', { values: { index: index + 1 } })}
                    onclick={() => removeStep(index)}>{$t('frameleaf_workflows.remove')}</Button
                  >
                </div>
              </li>
            {/each}
          </ol>
          {#if draft.steps.length === 0}<p>{$t('frameleaf_workflows.no_steps')}</p>{/if}
          <label class="wd-field">
            {$t('frameleaf_workflows.available_method')}
            <select bind:value={method}>
              {#each methods as item (item.key)}
                <option value={item.key}>{item.title}</option>
              {/each}
            </select>
          </label>
          <Button disabled={!method || draft.steps.length >= WORKFLOW_LIMITS.steps} onclick={addStep}>
            {$t('frameleaf_workflows.add_step')}
          </Button>
        </div>

        <section class="wd-parameters" aria-label={$t('frameleaf_workflows.step_details')}>
          <h3>
            {definition?.title ??
              (selected ? $t('frameleaf_workflows.unavailable_method') : $t('frameleaf_workflows.step_details'))}
          </h3>
          {#if definition?.description}<p>{definition.description}</p>{/if}
          {#if definition && definition.allowedHosts.length > 0}
            <p>{$t('frameleaf_workflows.contacts_hosts', { values: { hosts: definition.allowedHosts.join(', ') } })}</p>
          {/if}
          {#if selected}
            <label class="wd-check">
              <input
                type="checkbox"
                checked={selected.enabled}
                onchange={(event) => updateStep({ ...selected, enabled: event.currentTarget.checked })}
              />
              {$t('frameleaf_workflows.enable_step')}
            </label>
            {#if definition}
              <WorkflowParameter
                schema={methodSchema(definition)}
                value={selected.config ?? {}}
                label={$t('frameleaf_workflows.parameters')}
                storedSecrets={selected.storedSecrets}
                {references}
                onChange={(config) => updateStep({ ...selected, config: config as Record<string, unknown> })}
              />
              {#if selected.storedSecrets.length > 0}<small>{$t('frameleaf_workflows.credentials_note')}</small>{/if}
            {:else}
              <p>{$t('frameleaf_workflows.method_not_installed')}</p>
            {/if}
            <details>
              <summary>{$t('frameleaf_workflows.method_json')}</summary>
              <code>{selected.method}</code>
              <p>{$t('frameleaf_workflows.method_json_help')}</p>
              {#if parameterJson === null}
                <pre>{JSON.stringify(selected.config ?? null, null, 2)}</pre>
                <Button onclick={() => (parameterJson = JSON.stringify(selected.config ?? null, null, 2))}>
                  {$t('frameleaf_workflows.edit_parameter_json')}
                </Button>
              {:else}
                <textarea aria-label={$t('frameleaf_workflows.parameter_json')} rows={12} bind:value={parameterJson}
                ></textarea>
                <div class="wd-row">
                  <Button onclick={() => (parameterJson = null)}
                    >{$t('frameleaf_workflows.cancel_parameter_edits')}</Button
                  >
                  <Button onclick={applyParameters}>{$t('frameleaf_workflows.apply_parameters')}</Button>
                </div>
              {/if}
            </details>
          {/if}
        </section>
      </div>

      <div class="wd-danger">
        <Button onclick={() => (deleting = !deleting)}>{$t('frameleaf_workflows.delete_workflow')}</Button>
        {#if deleting}
          <p>{$t('frameleaf_workflows.delete_prompt')}</p>
          <Button onclick={() => void remove()}>{$t('frameleaf_workflows.confirm_delete')}</Button>
        {/if}
      </div>
    {:else if tab === 'validation'}
      <h3>{$t('frameleaf_workflows.validation_title')}</h3>
      <p>{$t('frameleaf_workflows.validation_help')}</p>
      <div>
        <Button onclick={() => (validation = previewWorkflow(draft, methods, triggers))}>
          {$t('frameleaf_workflows.validate')}
        </Button>
      </div>
      {#if validation}
        <div role="status">
          {#if validation.problems.length > 0}
            <ul>
              {#each validation.problems as problem, index (index)}<li>{problem.message}</li>{/each}
            </ul>
          {:else}
            <!-- WorkflowDesigner.jsx "Check and preview": a step-by-step dry run; nothing executes. -->
            <p>{$t('frameleaf_workflows.validation_ok')}</p>
            <ol class="wd-preview">
              {#each validation.steps as step (step.index)}
                <li>
                  <strong>{step.title ?? step.method}</strong>
                  <span>
                    {step.result === 'disabled'
                      ? $t('frameleaf_workflows.preview_step_disabled')
                      : $t('frameleaf_workflows.preview_step_validated')}
                  </span>
                </li>
              {/each}
            </ol>
            <p>{$t('frameleaf_workflows.preview_run_needs')}</p>
          {/if}
        </div>
      {/if}
    {:else if tab === 'history'}
      <h3>{$t('frameleaf_workflows.history_title')}</h3>
      <p>{$t('frameleaf_workflows.history_help')}</p>
      {#if notice}<p role="status">{notice}</p>{/if}
      {#if !workflow}
        <p>{$t('frameleaf_workflows.history_new')}</p>
      {:else if !workflow.logging}
        <p>{$t('frameleaf_workflows.history_off_help')}</p>
      {:else}
        <label class="wd-field">
          {$t('frameleaf_workflows.filter_all')}
          <select
            bind:value={logFilter}
            onchange={() => void loadLogs(true)}
            aria-label={$t('frameleaf_workflows.filter_all')}
          >
            <option value="">{$t('frameleaf_workflows.filter_all')}</option>
            <option value={WorkflowResult.Completed}>{$t('frameleaf_workflows.result_completed')}</option>
            <option value={WorkflowResult.Halted}>{$t('frameleaf_workflows.result_halted')}</option>
            <option value={WorkflowResult.Error}>{$t('frameleaf_workflows.result_error')}</option>
          </select>
        </label>
        {#if logs.length === 0 && !logsLoading}
          <p>{$t('frameleaf_workflows.history_empty')}</p>
        {:else}
          <table class="wd-history">
            <tbody>
              {#each logs as entry (entry.id)}
                <tr>
                  <td>
                    {DateTime.fromISO(entry.at).toLocaleString(DateTime.DATETIME_MED)}
                    <small>{attemptLabel(entry.attempt)}</small>
                  </td>
                  <td>
                    <strong>{resultLabel(entry)}</strong>
                    {#if entry.error}<small class="wd-error">{entry.error}</small>{/if}
                  </td>
                  <td>
                    {#if entry.triggerDataId}
                      <a href={Route.viewAsset({ id: entry.triggerDataId })}>{$t('frameleaf_workflows.open_photo')}</a>
                    {/if}
                    {#if entry.errorCode === WorkflowRunErrorCode.StepFailed && entry.triggerDataId && workflow.enabled}
                      <Button onclick={() => void retry(entry)}>{$t('frameleaf_workflows.retry')}</Button>
                    {/if}
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
          {#if logsMore}
            <Button disabled={logsLoading} onclick={() => void loadLogs(false)}
              >{$t('frameleaf_workflows.load_more')}</Button
            >
          {/if}
        {/if}
      {/if}
    {:else}
      <h3>{$t('frameleaf_workflows.json_title')}</h3>
      <p>{$t('frameleaf_workflows.json_help')}</p>
      <textarea
        class="wd-json"
        aria-label={$t('frameleaf_workflows.json_label')}
        spellcheck={false}
        rows={20}
        bind:value={raw}></textarea>
      <div class="wd-switches">
        <Button onclick={applyJson}>{$t('frameleaf_workflows.apply_json')}</Button>
        <Button disabled={jsonPending} onclick={() => downloadJson(exportDraft(draft), exportFileName(draft.name))}>
          {$t('frameleaf_workflows.export_definition')}
        </Button>
      </div>
    {/if}

    <div class="wd-actions">
      <Button onclick={cancel}>{$t('frameleaf_workflows.cancel')}</Button>
      <Button
        variant="primary"
        disabled={!!persistError || saving || parameterJson !== null || jsonPending}
        onclick={() => void save()}
      >
        {$t('frameleaf_workflows.save')}
      </Button>
    </div>
  </div>
</Dialog>

// design/frameleaf/template/src/WorkflowDesigner.jsx
import React, { useState } from "react";
import { Button, Dialog } from "./App";
import { SearchableSelect } from "./SearchableSelect";
import { tags, media } from "./media";
import {
  workflowMethods,
  workflowTemplates,
  workflowTriggers,
  methodByKey,
  schemaDefaults,
  parseWorkflowDefinition,
  migrateLegacyWorkflow,
  workflowExecutionErrors,
  workflowPersistenceError,
  exportWorkflowDefinition,
  updateWorkflowParameter,
} from "./workflow-schema.mjs";
import { previewWorkflow } from "./utilities-data.mjs";
import "./workflow-designer.css";
const referenceOptions = {
  TagId: tags,
  AlbumId: [...new Set(media.flatMap((asset) => asset.albumIds ?? []))].map(
    (id) => ({
      id,
      label:
        { "summer-rockies": "Summer in the Rockies", family: "Family" }[id] ??
        id,
    }),
  ),
};

function Parameter({
  schema,
  value,
  onChange,
  label,
  required = false,
  disabled = false,
}) {
  const isArray = schema.array || schema.type === "array";
  if (schema.properties || schema.type === "object")
    return (
      <fieldset className="wd-object" disabled={disabled}>
        <legend>
          {label}
          {required ? " *" : ""}
        </legend>
        {schema.description && <p>{schema.description}</p>}
        {Object.entries(schema.properties ?? {})
          .sort(
            (a, b) => (a[1].uiHint?.order ?? 99) - (b[1].uiHint?.order ?? 99),
          )
          .map(([key, child]) => (
            <Parameter
              key={key}
              label={child.title ?? key}
              schema={child}
              required={schema.required?.includes(key)}
              value={value?.[key]}
              disabled={disabled}
              onChange={(next) =>
                onChange(updateWorkflowParameter(value ?? {}, [key], next))
              }
            />
          ))}
      </fieldset>
    );
  if (isArray) {
    const entries = Array.isArray(value) ? value : [];
    const references = referenceOptions[schema.uiHint?.type];
    if (references)
      return (
        <fieldset className="wd-object" disabled={disabled}>
          <legend>
            {label}
            {required ? " *" : ""}
          </legend>
          <div className="wd-reference-values">
            {entries.map((id, index) => (
              <span key={`${index}:${id}`}>
                {references.find((item) => item.id === id)?.label ??
                  `Unavailable selection: ${id}`}
                <Button
                  disabled={disabled}
                  aria-label={`Remove ${references.find((item) => item.id === id)?.label ?? id}`}
                  onClick={() =>
                    onChange(entries.filter((_, i) => i !== index))
                  }
                >
                  Remove
                </Button>
              </span>
            ))}
          </div>
          <SearchableSelect
            disabled={disabled}
            label={
              schema.uiHint.type === "TagId" ? "Find a tag" : "Find an album"
            }
            value=""
            options={[
              { value: "", label: "Choose to add" },
              ...references
                .filter((item) => !entries.includes(item.id))
                .map((item) => ({ value: item.id, label: item.label })),
            ]}
            onChange={(id) => {
              if (id) onChange([...entries, id]);
            }}
          />
          <details>
            <summary>Advanced identifiers</summary>
            <textarea
              aria-label={`${label} identifiers`}
              disabled={disabled}
              value={entries.join("\n")}
              rows={3}
              onChange={(event) =>
                onChange(
                  event.target.value
                    .split("\n")
                    .map((item) => item.trim())
                    .filter(Boolean),
                )
              }
            />
            <small>
              Unresolved imported references remain selected until you remove or
              replace them.
            </small>
          </details>
        </fieldset>
      );
    return (
      <fieldset className="wd-object" disabled={disabled}>
        <legend>
          {label}
          {required ? " *" : ""}
        </legend>
        {schema.description && <p>{schema.description}</p>}
        {schema.enum ? (
          <div className="wd-enum-list">
            {[...new Set([...schema.enum, ...entries])].map((option) => (
              <label key={option}>
                <input
                  type="checkbox"
                  checked={entries.includes(option)}
                  onChange={(event) =>
                    onChange(
                      event.target.checked
                        ? [...entries, option]
                        : entries.filter((entry) => entry !== option),
                    )
                  }
                />
                {option}
                {!schema.enum.includes(option) ? " (unavailable)" : ""}
              </label>
            ))}
          </div>
        ) : (
          <label className="wd-field">
            {schema.uiHint?.type === "TagId"
              ? "Tag identifiers"
              : schema.uiHint?.type === "AlbumId"
                ? "Album identifiers"
                : "Values, one per line"}
            <textarea
              value={entries.join("\n")}
              rows={3}
              onChange={(event) =>
                onChange(
                  event.target.value
                    .split("\n")
                    .map((item) => item.trim())
                    .filter(Boolean),
                )
              }
            />
          </label>
        )}
        {schema.uiHint?.type && (
          <small>
            Use exact identifiers from accessible{" "}
            {schema.uiHint.type === "TagId" ? "tags" : "albums"}. Names do not
            replace identifiers.
          </small>
        )}
      </fieldset>
    );
  }
  if (schema.type === "boolean")
    return (
      <label className="wd-check">
        <input
          type="checkbox"
          checked={value === true}
          disabled={disabled}
          onChange={(event) => onChange(event.target.checked)}
        />
        <span>
          {label}
          <small>{schema.description}</small>
        </span>
      </label>
    );
  if (schema.enum)
    return (
      <label className="wd-field">
        {label}
        {required ? " *" : ""}
        <select
          disabled={disabled}
          value={value ?? ""}
          onChange={(event) => onChange(event.target.value)}
        >
          {!required && <option value="">Not set</option>}
          {value !== undefined && !schema.enum.includes(value) && (
            <option value={value}>Current: {String(value)}</option>
          )}
          {schema.enum.map((option) => (
            <option key={option} value={option}>
              {option}
            </option>
          ))}
        </select>
        <small>{schema.description}</small>
      </label>
    );
  return (
    <label className="wd-field">
      {label}
      {required ? " *" : ""}
      <input
        disabled={disabled}
        type={
          ["number", "integer"].includes(schema.type)
            ? "number"
            : label.toLowerCase().includes("header value")
              ? "password"
              : "text"
        }
        value={value ?? ""}
        min={schema.minimum}
        max={schema.maximum}
        step={schema.precision ?? (schema.type === "integer" ? 1 : "any")}
        autoComplete="off"
        onChange={(event) =>
          onChange(
            event.target.value === ""
              ? undefined
              : ["number", "integer"].includes(schema.type)
                ? Number(event.target.value)
                : event.target.value,
          )
        }
      />
      <small>{schema.description}</small>
    </label>
  );
}

export function WorkflowDesigner({ value, close, onSave, onRemove }) {
  const [draft, setDraft] = useState(() => migrateLegacyWorkflow(value));
  const [tab, setTab] = useState("Steps");
  const [active, setActive] = useState(0);
  const [method, setMethod] = useState(workflowMethods[0].key);
  const [template, setTemplate] = useState("");
  const [error, setError] = useState("");
  const [raw, setRaw] = useState(() =>
    JSON.stringify(migrateLegacyWorkflow(value), null, 2),
  );
  const [parameterJson, setParameterJson] = useState(null);
  const [validation, setValidation] = useState(null);
  const [deleting, setDeleting] = useState(false);
  const readOnly = value.ownerId !== "taylor";
  const selected = draft.steps[active];
  const definition = selected && methodByKey(selected.method);
  const problems = workflowExecutionErrors(draft);
  const persistError = workflowPersistenceError(draft);
  function update(next) {
    setDraft(next);
    setRaw(JSON.stringify(next, null, 2));
    setError("");
    setValidation(null);
  }
  function stepUpdate(next) {
    update({
      ...draft,
      steps: draft.steps.map((step, index) => (index === active ? next : step)),
    });
  }
  function move(index, offset) {
    const steps = [...draft.steps];
    const target = index + offset;
    if (target < 0 || target >= steps.length) return;
    [steps[index], steps[target]] = [steps[target], steps[index]];
    update({ ...draft, steps });
    setActive(target);
  }
  function save() {
    if (readOnly) return;
    const message = workflowPersistenceError(draft);
    if (message) {
      setError(message);
      return;
    }
    if (onSave({ ...draft, id: value.id, ownerId: value.ownerId }) === false)
      setError("Changes could not be saved. Your draft is still open.");
  }
  function download() {
    try {
      const data = exportWorkflowDefinition(draft);
      const url = URL.createObjectURL(
        new Blob([JSON.stringify(data, null, 2)], { type: "application/json" }),
      );
      const a = document.createElement("a");
      a.href = url;
      a.download = "frameleaf-workflow.json";
      a.click();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    } catch (error) {
      setError(error.message);
    }
  }
  function chooseTab(next) {
    setError("");
    if (next === "JSON") setRaw(JSON.stringify(draft, null, 2));
    setTab(next);
    setParameterJson(null);
  }
  return (
    <Dialog
      title={draft.name || "New workflow"}
      close={close}
      wide
      actions={
        <>
          <Button onClick={close}>Cancel</Button>
          <Button
            primary
            disabled={
              readOnly ||
              !!persistError ||
              parameterJson !== null ||
              (tab === "JSON" && raw !== JSON.stringify(draft, null, 2))
            }
            onClick={save}
          >
            Save workflow
          </Button>
        </>
      }
    >
      <div className="workflow-designer">
        <div className="wd-tabs" aria-label="Workflow sections">
          {["Steps", "Validation", "History", "JSON"].map((name) => (
            <Button
              key={name}
              aria-pressed={tab === name}
              onClick={() => chooseTab(name)}
            >
              {name}
            </Button>
          ))}
        </div>
        {readOnly && (
          <p className="wd-message">
            Only the workflow owner can change this definition.
          </p>
        )}
        {draft.legacyDefinition && (
          <p className="wd-message">
            An earlier sample definition was adapted to current workflow
            methods. Its original values remain included in the file.
          </p>
        )}
        {error && (
          <p role="alert" className="wd-error">
            {error}
          </p>
        )}
        {persistError && <p className="wd-message">{persistError}</p>}
        {tab === "Steps" && (
          <>
            <div className="wd-meta">
              <label className="wd-field">
                Name
                <input
                  value={draft.name ?? ""}
                  disabled={readOnly}
                  maxLength={300}
                  onChange={(event) =>
                    update({ ...draft, name: event.target.value || null })
                  }
                />
              </label>
              <label className="wd-field">
                Trigger
                <select
                  value={draft.trigger}
                  disabled={readOnly}
                  onChange={(event) =>
                    update({ ...draft, trigger: event.target.value })
                  }
                >
                  {!workflowTriggers.some(
                    (trigger) => trigger.value === draft.trigger,
                  ) && (
                    <option value={draft.trigger}>
                      {draft.trigger} (unavailable)
                    </option>
                  )}
                  {workflowTriggers.map((trigger) => (
                    <option key={trigger.value} value={trigger.value}>
                      {trigger.label}
                    </option>
                  ))}
                </select>
              </label>
              <label className="wd-field wd-description">
                Description
                <textarea
                  value={draft.description ?? ""}
                  disabled={readOnly}
                  rows={2}
                  onChange={(event) =>
                    update({
                      ...draft,
                      description: event.target.value || null,
                    })
                  }
                />
              </label>
            </div>
            <div className="wd-switches">
              <label>
                <input
                  type="checkbox"
                  disabled={readOnly || (!draft.enabled && problems.length > 0)}
                  checked={draft.enabled === true}
                  onChange={(event) =>
                    update({ ...draft, enabled: event.target.checked })
                  }
                />
                Enable workflow
              </label>
              <label>
                <input
                  type="checkbox"
                  disabled={readOnly}
                  checked={draft.logging !== false}
                  onChange={(event) =>
                    update({ ...draft, logging: event.target.checked })
                  }
                />
                Keep run history
              </label>
            </div>
            <div className="wd-template">
              <label>
                Start from a template
                <select
                  disabled={readOnly}
                  value={template}
                  onChange={(event) => setTemplate(event.target.value)}
                >
                  <option value="">Choose a template</option>
                  {workflowTemplates.map((item) => (
                    <option key={item.name} value={item.name}>
                      {item.title}
                    </option>
                  ))}
                </select>
              </label>
              {template && (
                <>
                  <p>
                    {
                      workflowTemplates.find((item) => item.name === template)
                        ?.description
                    }
                  </p>
                  <Button
                    disabled={readOnly}
                    onClick={() => {
                      const chosen = workflowTemplates.find(
                        (item) => item.name === template,
                      );
                      update({
                        ...draft,
                        trigger: chosen.trigger,
                        steps: structuredClone(chosen.steps),
                        name: draft.name || chosen.title,
                        description: draft.description || chosen.description,
                        enabled: false,
                      });
                      setActive(0);
                      setTemplate("");
                    }}
                  >
                    Replace current steps with template
                  </Button>
                </>
              )}
            </div>
            <div className="wd-workspace">
              <div className="wd-steps">
                <h3>Ordered steps</h3>
                <ol>
                  {draft.steps.map((step, index) => (
                    <li
                      key={index}
                      className={index === active ? "selected" : ""}
                    >
                      <button
                        className="wd-step-select"
                        onClick={() => {
                          setActive(index);
                          setParameterJson(null);
                        }}
                        aria-current={index === active ? "step" : undefined}
                      >
                        <strong>
                          {index + 1}.{" "}
                          {methodByKey(step.method)?.title ??
                            "Unavailable plugin method"}
                        </strong>
                        <small>
                          {step.enabled === false
                            ? "Disabled step"
                            : methodByKey(step.method)?.uiHints?.includes(
                                  "Filter",
                                )
                              ? "Filter"
                              : "Action"}
                        </small>
                      </button>
                      <div className="wd-step-actions">
                        <Button
                          disabled={readOnly || index === 0}
                          aria-label={`Move step ${index + 1} earlier`}
                          onClick={() => move(index, -1)}
                        >
                          ↑
                        </Button>
                        <Button
                          disabled={
                            readOnly || index === draft.steps.length - 1
                          }
                          aria-label={`Move step ${index + 1} later`}
                          onClick={() => move(index, 1)}
                        >
                          ↓
                        </Button>
                        <Button
                          disabled={readOnly}
                          aria-label={`Remove step ${index + 1}`}
                          onClick={() => {
                            update({
                              ...draft,
                              steps: draft.steps.filter((_, i) => i !== index),
                            });
                            setActive(
                              Math.max(
                                0,
                                Math.min(active, draft.steps.length - 2),
                              ),
                            );
                          }}
                        >
                          Remove
                        </Button>
                      </div>
                    </li>
                  ))}
                </ol>
                {!draft.steps.length && (
                  <p>Add a filter or an action to get started.</p>
                )}
                <SearchableSelect
                  label="Available method"
                  disabled={readOnly}
                  value={method}
                  options={workflowMethods.map((item) => ({
                    value: item.key,
                    label: item.title,
                  }))}
                  onChange={setMethod}
                />
                <Button
                  disabled={readOnly || !method || draft.steps.length >= 100}
                  onClick={() => {
                    const selected = methodByKey(method);
                    update({
                      ...draft,
                      steps: [
                        ...draft.steps,
                        {
                          method,
                          config: schemaDefaults(selected.schema ?? {}),
                          enabled: true,
                        },
                      ],
                    });
                    setActive(draft.steps.length);
                  }}
                >
                  Add step
                </Button>
              </div>
              <section className="wd-parameters">
                <h3>
                  {definition?.title ??
                    (selected ? "Unavailable method" : "Step details")}
                </h3>
                {definition?.description && <p>{definition.description}</p>}
                {selected && (
                  <>
                    <label className="wd-check">
                      <input
                        type="checkbox"
                        disabled={readOnly}
                        checked={selected.enabled !== false}
                        onChange={(event) =>
                          stepUpdate({
                            ...selected,
                            enabled: event.target.checked,
                          })
                        }
                      />
                      Enable this step
                    </label>
                    {definition ? (
                      <Parameter
                        schema={definition.schema ?? {}}
                        value={selected.config ?? {}}
                        label="Parameters"
                        disabled={readOnly}
                        onChange={(config) =>
                          stepUpdate({ ...selected, config })
                        }
                      />
                    ) : (
                      <p>
                        This method is not installed in the available catalog.
                        Its name, parameters and additional fields are retained.
                        It cannot be enabled or validated here.
                      </p>
                    )}
                    <details>
                      <summary>Method and parameter JSON</summary>
                      <code>{selected.method}</code>
                      <p>
                        Editing visible controls preserves other parameter
                        fields. Change the JSON only when you intend to replace
                        those values.
                      </p>
                      {parameterJson === null ? (
                        <>
                          <pre>
                            {JSON.stringify(selected.config ?? null, null, 2)}
                          </pre>
                          <Button
                            disabled={readOnly}
                            onClick={() =>
                              setParameterJson(
                                JSON.stringify(
                                  selected.config ?? null,
                                  null,
                                  2,
                                ),
                              )
                            }
                          >
                            Edit parameter JSON
                          </Button>
                        </>
                      ) : (
                        <>
                          <textarea
                            aria-label="Step parameter JSON"
                            value={parameterJson}
                            onChange={(event) =>
                              setParameterJson(event.target.value)
                            }
                            rows={12}
                          />
                          <Button onClick={() => setParameterJson(null)}>
                            Cancel parameter edits
                          </Button>
                          <Button
                            disabled={readOnly}
                            onClick={() => {
                              try {
                                const config = JSON.parse(parameterJson);
                                const next = { ...selected, config };
                                parseWorkflowDefinition({
                                  ...draft,
                                  steps: draft.steps.map((step, i) =>
                                    i === active ? next : step,
                                  ),
                                });
                                stepUpdate(next);
                                setParameterJson(null);
                              } catch (error) {
                                setError(error.message);
                              }
                            }}
                          >
                            Apply parameters
                          </Button>
                        </>
                      )}
                    </details>
                  </>
                )}
              </section>
            </div>
            <div className="wd-danger">
              <Button
                disabled={readOnly}
                onClick={() => setDeleting(!deleting)}
              >
                Delete workflow
              </Button>
              {deleting && (
                <>
                  <p>
                    Delete this definition? Previously changed photo metadata is
                    retained.
                  </p>
                  <Button
                    disabled={readOnly}
                    onClick={() => onRemove(value.id)}
                  >
                    Confirm workflow deletion
                  </Button>
                </>
              )}
            </div>
          </>
        )}
        {tab === "Validation" && (
          <>
            <h3>Check the definition</h3>
            <p>
              Validate method availability, required values, choices and ranges
              against the available plugin schemas. No photo is changed and no
              webhook is sent.
            </p>
            <Button
              onClick={() => setValidation(workflowExecutionErrors(draft))}
            >
              Check and preview
            </Button>
            {validation && (
              <div role="status">
                {validation.length ? (
                  <ul>
                    {validation.map((message, index) => (
                      <li key={index}>{message}</li>
                    ))}
                  </ul>
                ) : (
                  <>
                    <p>
                      The definition matches the available schemas. This is
                      what a run would do, step by step:
                    </p>
                    <ol className="wd-preview">
                      {previewWorkflow(draft).map((step, index) => (
                        <li key={index}>
                          <strong>
                            {methodByKey(step.method)?.title || step.method}
                          </strong>
                          <span>{step.result}</span>
                        </li>
                      ))}
                    </ol>
                    <p>
                      Running it still needs the server workflow service and
                      access to its selected albums and tags.
                    </p>
                  </>
                )}
              </div>
            )}
          </>
        )}
        {tab === "History" && (
          <>
            <h3>Workflow history</h3>
            <p>
              No server run history is available on this device. Definition
              validation does not create a completed run.
            </p>
          </>
        )}
        {tab === "JSON" && (
          <>
            <h3>Complete definition</h3>
            <p>
              Unknown plugin parameters and additional fields are kept.
              Unsupported definitions can be saved paused; enabling them
              requires a compatible plugin and trigger.
            </p>
            <textarea
              className="wd-json"
              aria-label="Workflow JSON"
              spellCheck={false}
              readOnly={readOnly}
              value={raw}
              onChange={(event) => setRaw(event.target.value)}
              rows={20}
            />
            <div className="wd-switches">
              <Button
                disabled={readOnly}
                onClick={() => {
                  try {
                    const next = parseWorkflowDefinition(raw);
                    update({ ...next, id: value.id, ownerId: value.ownerId });
                  } catch (error) {
                    setError(error.message);
                  }
                }}
              >
                Apply JSON to draft
              </Button>
              <Button
                disabled={raw !== JSON.stringify(draft, null, 2)}
                onClick={download}
              >
                Export complete definition
              </Button>
            </div>
          </>
        )}
      </div>
    </Dialog>
  );
}
