// design/frameleaf/template/src/FilterPanel.jsx
import React, { useEffect, useRef, useState } from "react";
import { Button } from "./App";
import { Icon } from "./Icon";
import { PersonAvatar } from "./People";
import { SearchableSelect } from "./SearchableSelect";
import {
  captureDateControlValue,
  captureDateHasCustomCondition,
  customConditionValue,
  equalityControlValue,
  flagToggleActive,
  moveSetGroup,
  ratingConditionForValue,
  ratingControlValue,
  setGroupLabels,
  statusConditionForValue,
  statusControlValue,
  toggleFlagCondition,
  updateCaptureDate,
  updateSetGroup,
} from "./filter-state.mjs";
import {
  descriptionStatuses,
  sensitiveStatuses,
  statusLabels,
} from "./search.mjs";
import "./filter-panel.css";

function MultiFilter({ field, label, items, condition, setCondition, people }) {
  const [term, setTerm] = useState("");
  const [preferred, setPreferred] = useState(null);
  const mode =
    preferred ||
    Object.keys(setGroupLabels).find((key) => condition?.[key]?.length) ||
    "any";
  const selected = condition?.[mode] || [];
  const update = (values) =>
    setCondition(field, updateSetGroup(condition, mode, values));
  const retainedGroups = Object.keys(setGroupLabels).filter(
    (key) => key !== mode && condition?.[key]?.length,
  );
  const activeGroupCount = Object.keys(setGroupLabels).filter(
    (group) => condition?.[group]?.length,
  ).length;
  return (
    <section className="filter-section">
      <div className="filter-section-heading">
        <h3>{label}</h3>
        <select
          aria-label={`${label} matching`}
          value={mode}
          onChange={(e) => {
            setCondition(field, moveSetGroup(condition, mode, e.target.value));
            setPreferred(e.target.value);
          }}
        >
          <option value="any">Any of</option>
          <option value="all">All of</option>
          <option value="none">Exclude</option>
        </select>
      </div>
      {activeGroupCount > 1 && (
        <p className="muted filter-group-help">
          Other selections remain active.
        </p>
      )}
      {retainedGroups.map((group) => (
        <p className="muted filter-group-summary" key={group}>
          {setGroupLabels[group]}:{" "}
          {condition[group]
            .map(
              (value) =>
                items.find((item) => item.value === value)?.label || value,
            )
            .join(", ")}{" "}
          <button
            type="button"
            className="text-button"
            onClick={() => setPreferred(group)}
            aria-label={`Edit ${label.toLowerCase()} ${setGroupLabels[group].toLowerCase()} group`}
          >
            Edit
          </button>
        </p>
      ))}
      {activeGroupCount > 0 && (
        <div className="filter-group-actions">
          {Object.keys(setGroupLabels)
            .filter((group) => group !== mode && !condition?.[group]?.length)
            .map((group) => (
              <button
                type="button"
                className="text-button"
                key={group}
                onClick={() => setPreferred(group)}
              >
                Add {setGroupLabels[group].toLowerCase()} group
              </button>
            ))}
        </div>
      )}
      <input
        className="filter-find"
        aria-label={`Find ${label.toLowerCase()}`}
        placeholder={`Find ${label.toLowerCase()}…`}
        value={term}
        onChange={(e) => setTerm(e.target.value)}
      />
      <div className={`filter-options ${people ? "face-options" : ""}`}>
        {items
          .filter((item) =>
            item.label.toLowerCase().includes(term.toLowerCase()),
          )
          .map((item) => (
            <label
              key={item.value}
              className={`filter-option ${selected.includes(item.value) ? "is-selected" : ""}`}
            >
              <input
                type="checkbox"
                checked={selected.includes(item.value)}
                onChange={() =>
                  update(
                    selected.includes(item.value)
                      ? selected.filter((value) => value !== item.value)
                      : [...selected, item.value],
                  )
                }
              />
              {people && (
                <PersonAvatar
                  person={people.find((person) => person.id === item.value)}
                  size={34}
                />
              )}
              <span>{item.label}</span>
              <small>{item.count}</small>
            </label>
          ))}
        {!items.some((item) =>
          item.label.toLowerCase().includes(term.toLowerCase()),
        ) && <p className="muted">No matching {label.toLowerCase()}.</p>}
      </div>
    </section>
  );
}
export function FilterPanel({
  query,
  facets,
  people,
  count,
  collection,
  setCondition,
  clear,
  close,
  save,
  focusSection = "people",
  // Inside the search palette: the palette owns Escape, focus and the count.
  embedded = false,
}) {
  const panel = useRef(null);
  const closeRef = useRef(close);
  closeRef.current = close;
  const filter = query.filter;
  useEffect(() => {
    if (embedded) return undefined;
    const previousFocus = document.activeElement;
    const onKeyDown = (event) => {
      if (event.key === "Escape" && !event.defaultPrevented) {
        event.preventDefault();
        closeRef.current();
      }
    };
    document.addEventListener("keydown", onKeyDown);
    return () => {
      document.removeEventListener("keydown", onKeyDown);
      if (previousFocus?.isConnected)
        previousFocus.focus?.({ preventScroll: true });
    };
  }, []);
  useEffect(() => {
    if (embedded) return;
    panel.current
      ?.querySelector(`[data-section="${focusSection}"]`)
      ?.scrollIntoView({ block: "nearest" });
    panel.current?.querySelector("h2")?.focus({ preventScroll: true });
  }, [focusSection, embedded]);
  const typeValue = equalityControlValue(filter.type, (value) =>
    ["IMAGE", "VIDEO"].includes(value),
  );
  const ratingValue = ratingControlValue(filter.rating);
  const selectFacet = (field, label) => {
    const value = equalityControlValue(filter[field]);
    const options = [
      { value: "", label: `Any ${label.toLowerCase()}` },
      ...(value === customConditionValue
        ? [
            {
              value: customConditionValue,
              label: "Custom condition (see chip)",
              disabled: true,
            },
          ]
        : []),
      ...(facets[field] || []),
    ];
    if (
      value &&
      value !== customConditionValue &&
      !options.some((item) => item.value === value)
    )
      options.push({ value, label: value, count: 0 });
    return (
      <SearchableSelect
        key={field}
        label={label}
        value={value}
        options={options}
        onChange={(next) => setCondition(field, next ? { eq: next } : null)}
        placeholder={`Search ${label.toLowerCase()}…`}
      />
    );
  };
  const flag = (field, label) => {
    const value = equalityControlValue(
      filter[field],
      (value) => typeof value === "boolean",
    );
    return (
      <label className="filter-select" key={field}>
        {label}
        <select
          aria-label={label}
          value={value}
          onChange={(e) =>
            setCondition(
              field,
              e.target.value === "" ? null : { eq: e.target.value === "true" },
            )
          }
        >
          <option value="">Any</option>
          {value === customConditionValue && (
            <option value={customConditionValue} disabled>
              Custom condition (see chip)
            </option>
          )}
          <option value="true">Yes</option>
          <option value="false">No</option>
        </select>
      </label>
    );
  };
  const statusGroup = (field, label, statuses) => {
    const value = statusControlValue(filter[field], statuses);
    const name = `filter-${field}`;
    const counts = Object.fromEntries(
      (facets[field] || []).map((item) => [item.value, item.count]),
    );
    return (
      <div
        className="filter-status-options"
        role="radiogroup"
        aria-label={label}
      >
        {value === customConditionValue && (
          <p className="muted filter-section-help">Custom condition (see chip)</p>
        )}
        {[["", "Any"], ...statuses.map((status) => [status, statusLabels[field][status]])].map(
          ([option, text]) => (
            <label
              key={option || "any"}
              className={value === option ? "is-selected" : ""}
            >
              <input
                type="radio"
                name={name}
                value={option}
                checked={value === option}
                onChange={() => {
                  const next = statusConditionForValue(option, statuses);
                  if (next !== undefined) setCondition(field, next);
                }}
              />
              <span>{text}</span>
              {option && <small>{counts[option] ?? 0}</small>}
            </label>
          ),
        )}
      </div>
    );
  };
  const quickToggle = (field, label, icon) => {
    const active = flagToggleActive(filter[field], false);
    const count = facets[field]?.find((item) => item.value === "false")?.count;
    return (
      <button
        type="button"
        key={field}
        aria-pressed={active}
        onClick={() =>
          setCondition(field, toggleFlagCondition(filter[field], false))
        }
      >
        <Icon name={icon} />
        {label}
        {Number.isInteger(count) && <small>{count}</small>}
      </button>
    );
  };
  return (
    <aside
      className={`filter-panel${embedded ? " embedded" : ""}`}
      aria-label="Library filters"
      ref={panel}
    >
      {!embedded && (
        <div className="filter-panel-header">
          <div>
            <h2 tabIndex={-1}>Filters</h2>
            <span className="muted" aria-live="polite">
              {count} matching · {collection}
            </span>
          </div>
          <Button icon="mdiClose" aria-label="Close filters" onClick={close} />
        </div>
      )}
      <div className="filter-panel-scroll">
        <div data-section="people">
          <MultiFilter
            field="personIds"
            label="People"
            items={facets.personIds || []}
            condition={filter.personIds}
            setCondition={setCondition}
            people={people}
          />
        </div>
        <section className="filter-section" data-section="media">
          <h3>Media</h3>
          {typeValue === customConditionValue && (
            <p className="muted">Custom condition (see chip)</p>
          )}
          <div className="filter-segments">
            {[
              ["", "All"],
              ["IMAGE", "Photos"],
              ["VIDEO", "Videos"],
            ].map(([value, label]) => (
              <button
                type="button"
                key={value}
                aria-pressed={typeValue === value}
                onClick={() =>
                  setCondition("type", value ? { eq: value } : null)
                }
              >
                {label}
                {value && (
                  <small>
                    {facets.type?.find((item) => item.value === value)?.count ||
                      0}
                  </small>
                )}
              </button>
            ))}
          </div>
        </section>
        <section className="filter-section" data-section="date">
          <h3>Capture date</h3>
          {captureDateHasCustomCondition(filter.takenAt) && (
            <p className="muted">
              Custom condition (see chip). Date controls edit one boundary at a
              time.
            </p>
          )}
          <div className="date-range">
            {[
              ["gte", "From"],
              ["lte", "Through"],
            ].map(([operator, label]) => (
              <label key={operator}>
                {label}
                <input
                  type="date"
                  aria-label={`Captured ${label.toLowerCase()}`}
                  value={captureDateControlValue(filter.takenAt, operator)}
                  onInput={(e) => {
                    setCondition(
                      "takenAt",
                      updateCaptureDate(
                        filter.takenAt,
                        operator,
                        e.target.value,
                      ),
                    );
                  }}
                />
              </label>
            ))}
          </div>
          <button
            type="button"
            className="text-button"
            onClick={() =>
              setCondition("takenAt", { gte: "2026-08-01", lte: "2026-08-31" })
            }
          >
            August 2026
          </button>
        </section>
        <section className="filter-section" data-section="places">
          <h3>Places</h3>
          {[
            ["country", "Country"],
            ["state", "State / province"],
            ["city", "City"],
          ].map(([field, label]) => selectFacet(field, label))}
        </section>
        <section className="filter-section" data-section="rating">
          <h3>Rating & favorites</h3>
          <SearchableSelect
            label="Rating"
            value={ratingValue}
            placeholder="Search ratings…"
            onChange={(value) => {
              const next = ratingConditionForValue(value);
              if (next !== undefined) setCondition("rating", next);
            }}
            options={[
              { value: "", label: "Any rating" },
              ...(ratingValue === customConditionValue
                ? [
                    {
                      value: customConditionValue,
                      label: "Custom condition (see chip)",
                      disabled: true,
                    },
                  ]
                : []),
              { value: "null", label: "No rating metadata" },
              { value: "0", label: "Unrated (0)" },
              { value: "-1", label: "Rejected" },
              ...[1, 2, 3, 4, 5].map((value) => ({
                value: String(value),
                label: `Exactly ${value} ${value === 1 ? "star" : "stars"}`,
              })),
              ...[0, 1, 2, 3, 4, 5].map((value) => ({
                value: `min${value}`,
                label: `${value} stars or more`,
              })),
            ]}
          />
          {flag("isFavorite", "Favorites")}
        </section>
        <div data-section="tags">
          <MultiFilter
            field="tagIds"
            label="Tags"
            items={facets.tagIds || []}
            condition={filter.tagIds}
            setCondition={setCondition}
          />
        </div>
        <section className="filter-section" data-section="camera">
          <h3>Camera & lens</h3>
          {[
            ["make", "Camera make"],
            ["model", "Camera model"],
            ["lensModel", "Lens"],
          ].map(([field, label]) => selectFacet(field, label))}
        </section>
        <section className="filter-section" data-section="text">
          <h3>Text & descriptions</h3>
          <p className="filter-section-help">
            Generated descriptions come from image enrichment; manual ones
            were written by a person.
          </p>
          {statusGroup("descriptionStatus", "Description", descriptionStatuses)}
        </section>
        <section className="filter-section" data-section="sensitivity">
          <h3>Sensitivity review</h3>
          <p className="filter-section-help">
            Items flagged by detection wait for a review; overridden items keep
            a person’s decision.
          </p>
          {statusGroup("sensitiveStatus", "Review status", sensitiveStatuses)}
        </section>
        <section className="filter-section" data-section="status">
          <h3>Library status</h3>
          <div className="filter-toggles" aria-label="Quick status filters">
            {quickToggle("hasAlbums", "Not in any album", "mdiImageAlbum")}
            {quickToggle("hasTags", "Untagged", "mdiTagOutline")}
          </div>
          {selectFacet("visibility", "Visibility")}
          {[
            ["hasPeople", "Has people"],
            ["hasAlbums", "In an album"],
            ["hasTags", "Has tags"],
          ].map(([field, label]) => flag(field, label))}
        </section>
      </div>
      <div className="filter-panel-footer">
        <Button onClick={clear}>Reset filters</Button>
        {!embedded && (
          <Button icon="mdiFolderSearchOutline" onClick={save}>
            Save preset
          </Button>
        )}
      </div>
    </aside>
  );
}

// web/src/lib/components/frameleaf/FilterPanel.svelte
<script lang="ts">
  import Button from '$lib/components/frameleaf/Button.svelte';
  import FilterMultiSelect from '$lib/components/frameleaf/FilterMultiSelect.svelte';
  import Picker from '$lib/components/frameleaf/Picker.svelte';
  import SegmentedControl from '$lib/components/frameleaf/SegmentedControl.svelte';
  import type { ComboBoxOption } from '$lib/components/shared-components/Combobox.svelte';
  import {
    withDiscoveryEnrichment,
    withoutDiscoveryFilters,
    type DiscoveryFilterSection,
    type DiscoveryQuery,
  } from '$lib/components/discovery/query';
  import {
    captureDateControlValue,
    captureDateHasCustomCondition,
    CUSTOM_CONDITION,
    ENRICHMENT_OPTIONS,
    equalityControlValue,
    flagToggleActive,
    ratingConditionForValue,
    ratingControlValue,
    toggleFlagCondition,
    updateCaptureDate,
    withFilterCondition,
    type SetCondition,
  } from '$lib/frameleaf/search-filters';
  import type { FilterPanelOptions } from '$lib/frameleaf/search-options';
  import '$lib/frameleaf/tokens.css';
  import { AssetTypeEnum, AssetVisibility, ImageEnrichmentFilter } from '@immich/sdk';
  import { t } from 'svelte-i18n';

  /**
   * The full Frameleaf filter panel (FL-49), ported from `design/frameleaf/template/src/FilterPanel.jsx`.
   *
   * FL-33 owns the Filter control in the results toolbar; this is the panel that control opens,
   * and `section` is the deep link it passes. Every control writes a condition on a real
   * `SearchFilter` field, or — for enrichment — the real `imageEnrichment` DTO enum. Where a
   * stored condition is richer than a control can express, the control reads "custom
   * condition (see chip)", makes no edit of its own and leaves the chip as the way to clear it.
   *
   * The panel is a controlled component: it never mutates the query it is given, it hands a new
   * one to `onChange`. Option lists (people, tags, albums, places, cameras) come from the caller,
   * which loads them from the production APIs.
   */

  let {
    query,
    options,
    section = 'people',
    matchingLabel,
    scopeLabel,
    onChange,
    onClose,
  }: {
    query: DiscoveryQuery;
    options: FilterPanelOptions;
    /** Which section the Filter control deep-linked into. */
    section?: DiscoveryFilterSection;
    /** Already-translated live count, e.g. "1,204 matching items". */
    matchingLabel?: string;
    /** Already-translated name of the scope being filtered. */
    scopeLabel?: string;
    onChange: (query: DiscoveryQuery) => void;
    onClose?: () => void;
  } = $props();

  let panel = $state<HTMLElement>();
  let heading = $state<HTMLElement>();

  const filter = $derived(query.filter as Record<string, Record<string, unknown> | undefined>);

  /**
   * The Filter menu's sections and the panel's anchors are the same vocabulary, so a deep link
   * is a scroll to the matching `data-section`. `all` opens at the top, which is where the
   * fields no other section claims already are.
   */
  $effect(() => {
    const target = section === 'all' ? undefined : panel?.querySelector(`[data-section="${CSS.escape(section)}"]`);
    target?.scrollIntoView({ block: 'nearest' });
    heading?.focus({ preventScroll: true });
  });

  const setCondition = (field: string, condition: Record<string, unknown> | SetCondition | null) =>
    onChange(withFilterCondition(query, field, condition as Record<string, unknown> | null));

  const asOption = (value: string, label: string): ComboBoxOption => ({ value, label });

  /**
   * A single-value facet select over a list of values the account's own library reports. An
   * unrecognised stored value is still offered, so opening the panel on a shared URL never
   * silently drops the condition it carries.
   */
  const facetOptions = (field: string, label: string, values: string[]): ComboBoxOption[] => {
    const current = equalityControlValue(filter[field]);
    const list = [asOption('', $t('frameleaf_search_any_of_field', { values: { label: label.toLowerCase() } }))];
    if (current === CUSTOM_CONDITION) {
      list.push(asOption(CUSTOM_CONDITION, $t('frameleaf_search_custom_condition')));
    }
    for (const value of values) {
      list.push(asOption(value, value));
    }
    if (current && current !== CUSTOM_CONDITION && !values.includes(current)) {
      list.push(asOption(current, current));
    }
    return list;
  };

  const selectedFacet = (field: string, label: string, values: string[]) => {
    const current = equalityControlValue(filter[field]);
    return facetOptions(field, label, values).find((option) => option.value === current);
  };

  const onFacet = (field: string) => (option: ComboBoxOption | undefined) => {
    const value = option?.value ?? '';
    if (value === CUSTOM_CONDITION) {
      // The disabled placeholder is not an edit; leave the stored condition alone.
      return;
    }
    setCondition(field, value ? { eq: value } : null);
  };

  const typeValue = $derived(
    equalityControlValue(filter.type, (value) => value === AssetTypeEnum.Image || value === AssetTypeEnum.Video),
  );
  const ratingValue = $derived(ratingControlValue(filter.rating));
  const visibilityValue = $derived(
    equalityControlValue(filter.visibility, (value) =>
      Object.values(AssetVisibility).includes(value as AssetVisibility),
    ),
  );

  const ratingOptions = $derived<ComboBoxOption[]>([
    asOption('', $t('frameleaf_search_any_rating')),
    ...(ratingValue === CUSTOM_CONDITION ? [asOption(CUSTOM_CONDITION, $t('frameleaf_search_custom_condition'))] : []),
    asOption('null', $t('frameleaf_search_rating_unset')),
    asOption('0', $t('frameleaf_search_rating_unrated')),
    asOption('-1', $t('frameleaf_search_rating_rejected')),
    ...[1, 2, 3, 4, 5].map((value) =>
      asOption(String(value), $t('frameleaf_search_rating_exactly', { values: { count: value } })),
    ),
    ...[0, 1, 2, 3, 4, 5].map((value) =>
      asOption(`min${value}`, $t('frameleaf_search_rating_at_least', { values: { count: value } })),
    ),
  ]);

  const enrichmentOptions = $derived<ComboBoxOption[]>([
    asOption('', $t('all')),
    ...ENRICHMENT_OPTIONS.map((option) => asOption(option.value, $t(option.labelKey))),
  ]);

  const flagOptions = $derived<ComboBoxOption[]>([
    asOption('', $t('frameleaf_search_any')),
    asOption('true', $t('yes')),
    asOption('false', $t('no')),
  ]);

  const placeFacets = $derived([
    { field: 'country', label: $t('country'), values: options.countries },
    { field: 'state', label: $t('state'), values: options.states },
    { field: 'city', label: $t('city'), values: options.cities },
  ]);

  const cameraFacets = $derived([
    { field: 'make', label: $t('camera_brand'), values: options.makes },
    { field: 'model', label: $t('camera_model'), values: options.models },
    { field: 'lensModel', label: $t('lens_model'), values: options.lenses },
  ]);

  const statusFlags = $derived([
    { field: 'hasPeople', label: $t('frameleaf_search_has_people') },
    { field: 'hasAlbums', label: $t('frameleaf_search_in_an_album') },
    { field: 'hasTags', label: $t('frameleaf_search_tagged') },
    { field: 'isMotion', label: $t('motion') },
    { field: 'isOffline', label: $t('offline') },
  ]);

  const dateBounds = $derived([
    { operator: 'gte' as const, label: $t('start_date') },
    { operator: 'lte' as const, label: $t('end_date') },
  ]);

  const visibilityOptions = $derived(facetOptions('visibility', $t('visibility'), Object.values(AssetVisibility)));

  const flagValue = (field: string) => equalityControlValue(filter[field], (value) => typeof value === 'boolean');

  const onFlag = (field: string) => (option: ComboBoxOption | undefined) => {
    const value = option?.value ?? '';
    if (value === CUSTOM_CONDITION) {
      return;
    }
    setCondition(field, value === '' ? null : { eq: value === 'true' });
  };
</script>

<aside class="filter-panel frameleaf" aria-label={$t('frameleaf_search_filters')} bind:this={panel}>
  <header>
    <div>
      <h2 tabindex="-1" bind:this={heading}>{$t('frameleaf_search_filters')}</h2>
      {#if matchingLabel || scopeLabel}
        <p class="muted" aria-live="polite">{[matchingLabel, scopeLabel].filter(Boolean).join(' · ')}</p>
      {/if}
    </div>
    {#if onClose}
      <Button variant="quiet" label={$t('frameleaf_search_close_filters')} onclick={onClose}>
        <span aria-hidden="true">&times;</span>
      </Button>
    {/if}
  </header>

  <div class="scroll">
    <FilterMultiSelect
      field="personIds"
      anchor="people"
      label={$t('people')}
      options={options.people.map((person) => ({ value: person.id, label: person.name || $t('no_name') }))}
      condition={filter.personIds as SetCondition}
      people={options.people}
      onChange={setCondition}
    />

    <!-- FL-58: shown once the account has a pet, or while a link carries a pet condition to remove -->
    {#if options.pets.length > 0 || filter.petIds}
      <FilterMultiSelect
        field="petIds"
        anchor="pets"
        label={$t('frameleaf_pets_title')}
        options={options.pets.map((pet) => ({ value: pet.id, label: pet.name || $t('frameleaf_pets_unnamed') }))}
        condition={filter.petIds as SetCondition}
        onChange={setCondition}
      />
    {/if}

    <section class="filter-section" data-section="media">
      <h3>{$t('media_type')}</h3>
      {#if typeValue === CUSTOM_CONDITION}
        <p class="muted">{$t('frameleaf_search_custom_condition')}</p>
      {/if}
      <SegmentedControl
        label={$t('media_type')}
        value={typeValue === CUSTOM_CONDITION ? '' : typeValue}
        options={[
          { value: '', label: $t('all') },
          { value: AssetTypeEnum.Image, label: $t('photos') },
          { value: AssetTypeEnum.Video, label: $t('videos') },
        ]}
        onChange={(value) => setCondition('type', value ? { eq: value } : null)}
      />
    </section>

    <section class="filter-section" data-section="date">
      <h3>{$t('frameleaf_search_field_taken_at')}</h3>
      {#if captureDateHasCustomCondition(filter.takenAt)}
        <p class="muted">{$t('frameleaf_search_date_custom_condition')}</p>
      {/if}
      <div class="dates">
        {#each dateBounds as bound (bound.operator)}
          <label>
            {bound.label}
            <input
              type="date"
              value={captureDateControlValue(filter.takenAt, bound.operator)}
              oninput={(event) =>
                setCondition('takenAt', updateCaptureDate(filter.takenAt, bound.operator, event.currentTarget.value))}
            />
          </label>
        {/each}
      </div>
    </section>

    <section class="filter-section" data-section="places">
      <h3>{$t('places')}</h3>
      {#each placeFacets as facet (facet.field)}
        <Picker
          label={facet.label}
          options={facetOptions(facet.field, facet.label, facet.values)}
          selectedOption={selectedFacet(facet.field, facet.label, facet.values)}
          onSelect={onFacet(facet.field)}
        />
      {/each}
    </section>

    <section class="filter-section" data-section="rating">
      <h3>{$t('frameleaf_search_rating_and_favorites')}</h3>
      <Picker
        label={$t('rating')}
        options={ratingOptions}
        selectedOption={ratingOptions.find((option) => option.value === ratingValue)}
        onSelect={(option) => {
          if (option?.value === CUSTOM_CONDITION) {
            return;
          }
          const next = ratingConditionForValue(option?.value ?? '');
          if (next !== undefined) {
            setCondition('rating', next);
          }
        }}
      />
      <Picker
        label={$t('favorites')}
        options={flagOptions}
        selectedOption={flagOptions.find((option) => option.value === flagValue('isFavorite'))}
        onSelect={onFlag('isFavorite')}
      />
    </section>

    <FilterMultiSelect
      field="tagIds"
      anchor="tags"
      label={$t('tags')}
      options={options.tags}
      condition={filter.tagIds as SetCondition}
      onChange={setCondition}
    />

    <FilterMultiSelect
      field="albumIds"
      anchor="albums"
      label={$t('albums')}
      options={options.albums}
      condition={filter.albumIds as SetCondition}
      onChange={setCondition}
    />

    <section class="filter-section" data-section="camera">
      <h3>{$t('frameleaf_search_camera_and_lens')}</h3>
      {#each cameraFacets as facet (facet.field)}
        <Picker
          label={facet.label}
          options={facetOptions(facet.field, facet.label, facet.values)}
          selectedOption={selectedFacet(facet.field, facet.label, facet.values)}
          onSelect={onFacet(facet.field)}
        />
      {/each}
    </section>

    <section class="filter-section" data-section="enrichment">
      <h3>{$t('image_enrichment')}</h3>
      <p class="muted">{$t('frameleaf_search_enrichment_help')}</p>
      <Picker
        label={$t('image_enrichment')}
        options={enrichmentOptions}
        selectedOption={enrichmentOptions.find((option) => option.value === (query.imageEnrichment ?? ''))}
        onSelect={(option) =>
          onChange(withDiscoveryEnrichment(query, (option?.value || undefined) as ImageEnrichmentFilter | undefined))}
      />
    </section>

    <section class="filter-section" data-section="status">
      <h3>{$t('frameleaf_search_library_status')}</h3>
      <div class="toggles" role="group" aria-label={$t('frameleaf_search_quick_status')}>
        <!-- The two quick toggles named in the September 22 revision. Both are ordinary
             SearchFilter boolean conditions, so the chip row can remove them like any other. -->
        <Button
          pressed={flagToggleActive(filter.hasAlbums, false)}
          onclick={() => setCondition('hasAlbums', toggleFlagCondition(filter.hasAlbums, false))}
        >
          {$t('not_in_any_album')}
        </Button>
        <Button
          pressed={flagToggleActive(filter.hasTags, false)}
          onclick={() => setCondition('hasTags', toggleFlagCondition(filter.hasTags, false))}
        >
          {$t('untagged')}
        </Button>
      </div>

      <Picker
        label={$t('visibility')}
        options={visibilityOptions}
        selectedOption={visibilityOptions.find((option) => option.value === visibilityValue)}
        onSelect={onFacet('visibility')}
      />

      {#each statusFlags as flag (flag.field)}
        <Picker
          label={flag.label}
          options={flagOptions}
          selectedOption={flagOptions.find((option) => option.value === flagValue(flag.field))}
          onSelect={onFlag(flag.field)}
        />
      {/each}
    </section>
  </div>

  <footer>
    <Button onclick={() => onChange(withoutDiscoveryFilters(query))}>{$t('frameleaf_search_reset_filters')}</Button>
  </footer>
</aside>

<style>
  .filter-panel {
    display: flex;
    flex-direction: column;
    min-height: 0;
    color: var(--fl-text);
    background: var(--fl-panel);
  }
  header,
  footer {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 0.75rem;
    padding-block: 0.75rem;
  }
  footer {
    border-top: 1px solid var(--fl-border);
  }
  h2 {
    font-size: 1rem;
    font-weight: 600;
  }
  h3 {
    font-size: 0.875rem;
    font-weight: 600;
  }
  .muted {
    font-size: var(--fl-font-small);
    color: var(--fl-muted);
  }
  .scroll {
    min-height: 0;
    overflow-y: auto;
  }
  .filter-section {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    padding-block: 0.875rem;
    border-bottom: 1px solid var(--fl-border);
  }
  .dates {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(9rem, 1fr));
    gap: 0.75rem;
  }
  .dates label {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
    font-size: var(--fl-font-small);
    color: var(--fl-muted);
  }
  .dates input {
    color: var(--fl-text);
    background: var(--fl-raised);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius-control);
    padding: 0.375rem 0.5rem;
    min-height: 36px;
  }
  .toggles {
    display: flex;
    flex-wrap: wrap;
    gap: 0.5rem;
  }
</style>
