// design/frameleaf/template/src/QrCode.jsx
import React, { useEffect, useMemo, useRef, useState } from "react";
import { Icon } from "./Icon";
import { encodeQr, qrPath } from "./qr.mjs";
import "./sharing.css";

const QUIET = 4;

/** Copy text to the clipboard, falling back to a hidden textarea. */
export async function copyText(text) {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    // fall through to the legacy path
  }
  try {
    const area = document.createElement("textarea");
    area.value = text;
    area.setAttribute("readonly", "");
    area.style.position = "fixed";
    area.style.opacity = "0";
    document.body.append(area);
    area.select();
    const ok = document.execCommand?.("copy") ?? false;
    area.remove();
    return !!ok;
  } catch {
    return false;
  }
}

function safeFileName(name) {
  return (
    String(name || "frameleaf-link")
      .replace(/[^A-Za-z0-9._-]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "frameleaf-link"
  );
}

/** Draw the matrix into a canvas and trigger a PNG download. */
export function downloadQrPng(modules, fileName, scale = 8) {
  const size = (modules.length + QUIET * 2) * scale;
  const canvas = document.createElement("canvas");
  canvas.width = size;
  canvas.height = size;
  const context = canvas.getContext("2d");
  if (!context) return false;
  context.fillStyle = "#ffffff";
  context.fillRect(0, 0, size, size);
  context.fillStyle = "#101112";
  modules.forEach((row, y) =>
    row.forEach((dark, x) => {
      if (dark)
        context.fillRect((x + QUIET) * scale, (y + QUIET) * scale, scale, scale);
    }),
  );
  const finish = (href, revoke) => {
    const anchor = document.createElement("a");
    anchor.href = href;
    anchor.download = `${safeFileName(fileName)}.png`;
    document.body.append(anchor);
    anchor.click();
    anchor.remove();
    if (revoke) setTimeout(() => URL.revokeObjectURL(href), 1000);
  };
  if (typeof canvas.toBlob === "function")
    canvas.toBlob((blob) => {
      if (blob) finish(URL.createObjectURL(blob), true);
      else finish(canvas.toDataURL("image/png"), false);
    }, "image/png");
  else finish(canvas.toDataURL("image/png"), false);
  return true;
}

/**
 * QR code for a URL, rendered as SVG with a quiet zone and optional
 * "Copy link" / "Download PNG" actions.
 */
export function QrCode({
  value,
  size = 220,
  ecc = "M",
  label = "QR code",
  fileName,
  showActions = true,
  onCopied,
}) {
  const [status, setStatus] = useState("");
  const timer = useRef(null);
  const encoded = useMemo(() => {
    try {
      return { symbol: encodeQr(String(value ?? ""), { ecc }) };
    } catch {
      return { error: "This link is too long to fit in a QR code." };
    }
  }, [value, ecc]);
  useEffect(() => () => clearTimeout(timer.current), []);
  const announce = (message) => {
    setStatus(message);
    clearTimeout(timer.current);
    timer.current = setTimeout(() => setStatus(""), 2500);
  };
  const copy = async () => {
    const ok = await copyText(String(value ?? ""));
    announce(ok ? "Link copied." : "Copying is not available here. Select the address instead.");
    if (ok) onCopied?.();
  };
  if (encoded.error)
    return (
      <div className="qr qr-error" role="status">
        <Icon name="mdiQrcode" />
        <span>{encoded.error}</span>
      </div>
    );
  const { modules } = encoded.symbol;
  const extent = modules.length + QUIET * 2;
  return (
    <figure className="qr">
      <svg
        className="qr-svg"
        role="img"
        aria-label={`${label} for ${value}`}
        viewBox={`0 0 ${extent} ${extent}`}
        width={size}
        height={size}
        shapeRendering="crispEdges"
      >
        <rect width={extent} height={extent} fill="#ffffff" />
        <path d={qrPath(modules, QUIET)} fill="#101112" />
      </svg>
      {showActions && (
        <figcaption className="qr-actions">
          <button type="button" className="button" onClick={copy}>
            <Icon name="mdiContentCopy" />
            Copy link
          </button>
          <button
            type="button"
            className="button"
            onClick={() => {
              const ok = downloadQrPng(modules, fileName || label);
              announce(ok ? "PNG saved to your downloads." : "PNG export is not available here.");
            }}
          >
            <Icon name="mdiDownloadOutline" />
            Download PNG
          </button>
        </figcaption>
      )}
      <span className="qr-status" role="status" aria-live="polite">
        {status}
      </span>
    </figure>
  );
}

// web/src/lib/components/frameleaf/QrCode.svelte
<script lang="ts">
  import { encodeQr, qrPath } from '$lib/frameleaf/qr';
  import { copyToClipboard } from '$lib/utils';

  const QUIET = 4;

  let {
    value,
    size = 220,
    label,
    copyLabel,
    downloadLabel,
    errorLabel,
    fileName,
    showActions = true,
  }: {
    /** The URL encoded in the code. Never a password or other secret. */
    value: string;
    size?: number;
    label: string;
    copyLabel: string;
    downloadLabel: string;
    errorLabel: string;
    fileName?: string;
    showActions?: boolean;
  } = $props();

  const encoded = $derived.by(() => {
    try {
      return { symbol: encodeQr(value, { ecc: 'M' }) };
    } catch {
      return { error: errorLabel };
    }
  });

  const safeFileName = (name: string | undefined) =>
    (name || 'frameleaf-link')
      .replaceAll(/[^\w.-]+/g, '-')
      .replaceAll(/^-+|-+$/g, '')
      .slice(0, 60) || 'frameleaf-link';

  const downloadPng = () => {
    if (!('symbol' in encoded) || !encoded.symbol) {
      return;
    }
    const { modules } = encoded.symbol;
    const scale = 8;
    const extent = (modules.length + QUIET * 2) * scale;
    const canvas = document.createElement('canvas');
    canvas.width = extent;
    canvas.height = extent;
    const context = canvas.getContext('2d');
    if (!context) {
      return;
    }
    context.fillStyle = '#ffffff';
    context.fillRect(0, 0, extent, extent);
    context.fillStyle = '#101112';
    for (const [y, row] of modules.entries()) {
      for (const [x, dark] of row.entries()) {
        if (dark) {
          context.fillRect((x + QUIET) * scale, (y + QUIET) * scale, scale, scale);
        }
      }
    }
    const finish = (href: string, revoke: boolean) => {
      const anchor = document.createElement('a');
      anchor.href = href;
      anchor.download = `${safeFileName(fileName)}.png`;
      document.body.append(anchor);
      anchor.click();
      anchor.remove();
      if (revoke) {
        setTimeout(() => URL.revokeObjectURL(href), 1000);
      }
    };
    canvas.toBlob((blob) => {
      if (blob) {
        finish(URL.createObjectURL(blob), true);
      } else {
        finish(canvas.toDataURL('image/png'), false);
      }
    }, 'image/png');
  };
</script>

{#if 'error' in encoded}
  <p class="qr-error" role="status">{encoded.error}</p>
{:else}
  {@const { modules } = encoded.symbol}
  {@const extent = modules.length + QUIET * 2}
  <figure class="qr">
    <svg
      class="qr-svg"
      role="img"
      aria-label={`${label} for ${value}`}
      viewBox={`0 0 ${extent} ${extent}`}
      width={size}
      height={size}
      shape-rendering="crispEdges"
    >
      <rect width={extent} height={extent} fill="#ffffff" />
      <path d={qrPath(modules, QUIET)} fill="#101112" />
    </svg>
    {#if showActions}
      <figcaption class="qr-actions">
        <button type="button" onclick={() => copyToClipboard(value)}>{copyLabel}</button>
        <button type="button" onclick={downloadPng}>{downloadLabel}</button>
      </figcaption>
    {/if}
  </figure>
{/if}

<style>
  .qr {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 0.75rem;
    margin: 0;
  }
  .qr-svg {
    background: #ffffff;
    border-radius: var(--fl-radius);
    padding: 0.5rem;
  }
  .qr-actions {
    display: flex;
    gap: 0.5rem;
  }
  .qr-actions button {
    background: var(--fl-raised);
    color: var(--fl-text);
    border: 1px solid var(--fl-border);
    border-radius: var(--fl-radius);
    padding: 0 0.75rem;
  }
  .qr-error {
    color: var(--fl-muted);
  }
</style>
